# generated by astra
import asyncio, collections, ctypes, hashlib, hmac, inspect, json, math, os, pathlib, socket, subprocess, sys, threading, time
_astra_gpu_runtime = _astra_gpu_get_runtime() if '_astra_gpu_get_runtime' in globals() else None
_astra_heap = {}
_astra_next_ptr = 1
_astra_threads = {}
_astra_next_tid = 1
_astra_atomics = {}
_astra_next_atomic = 1
_astra_atomic_lock = threading.Lock()
_astra_mutexes = {}
_astra_next_mutex = 1
_astra_channels = {}
_astra_next_chan = 1
_astra_sockets = {}
_astra_next_sock = 1
_astra_libs = {}
def __astra_cast(v, t):
    if t in ('Float', 'f32', 'f64'):
        return float(v)
    if t in ('Int', 'isize'): bits, signed = 64, True
    elif t == 'usize': bits, signed = 64, False
    elif t.startswith('i') and t[1:].isdigit(): bits, signed = int(t[1:]), True
    elif t.startswith('u') and t[1:].isdigit(): bits, signed = int(t[1:]), False
    else: return v
    if isinstance(v, float):
        if v != v: return 0
        if v == float('inf'):
            return (1 << (bits - 1)) - 1 if signed else (1 << bits) - 1
        if v == float('-inf'):
            return (-(1 << (bits - 1))) if signed else 0
        v = int(v)
    else:
        v = int(v)
    mask = (1 << bits) - 1
    out = v & mask
    if signed and out >= (1 << (bits - 1)):
        out -= (1 << bits)
    return out
def print_(x): print(x); return None
class _AstraTryNone(Exception):
    pass
class _AstraTryResultErr(Exception):
    def __init__(self, value):
        super().__init__('result-err')
        self.value = value
def __astra_result_err(v):
    return {'__enum__': 'Result', 'tag': 'Err', 'values': [v]}
def __astra_try_unwrap(v):
    if v is None:
        raise _AstraTryNone()
    return v
def __astra_try_unwrap_result(v):
    if isinstance(v, dict) and v.get('__enum__') == 'Result':
        tag = v.get('tag')
        vals = v.get('values')
        if not isinstance(vals, list):
            vals = []
        if tag == 'Ok':
            return vals[0] if vals else None
        if tag == 'Err':
            raise _AstraTryResultErr(vals[0] if vals else None)
    raise TypeError('`!` on Result expected Result.Ok/Result.Err value')
def len_(x): return len(x)
def read_file(p): return pathlib.Path(p).read_text()
def write_file(p,s): pathlib.Path(p).write_text(str(s)); return 0
def args(): return sys.argv
def arg(i): return sys.argv[i] if 0 <= int(i) < len(sys.argv) else ''
def alloc(n):
    global _astra_next_ptr
    ptr = _astra_next_ptr
    _astra_next_ptr += 1
    _astra_heap[ptr] = bytearray(max(0, int(n)))
    return ptr
def free(ptr):
    _astra_heap.pop(ptr, None)
    return None
def spawn(fn, *a):
    global _astra_next_tid
    tid = _astra_next_tid
    _astra_next_tid += 1
    state = {'done': False, 'result': 0, 'thread': None}
    def _runner():
        try:
            out = fn(*a)
            if inspect.isawaitable(out):
                out = asyncio.run(out)
            state['result'] = out
        except Exception:
            state['result'] = 0
        finally:
            state['done'] = True
    th = threading.Thread(target=_runner, daemon=False)
    state['thread'] = th
    _astra_threads[tid] = state
    th.start()
    return tid
def join(tid):
    state = _astra_threads.get(int(tid))
    if state is None:
        return 0
    th = state.get('thread')
    if th is not None:
        th.join()
    return state['result']
def await_result(v):
    if inspect.isawaitable(v):
        return asyncio.run(v)
    return v
def atomic_int_new(v):
    global _astra_next_atomic
    with _astra_atomic_lock:
        h = _astra_next_atomic
        _astra_next_atomic += 1
        _astra_atomics[h] = int(v)
    return h
def atomic_load(h):
    with _astra_atomic_lock:
        return int(_astra_atomics.get(int(h), 0))
def atomic_store(h, v):
    with _astra_atomic_lock:
        _astra_atomics[int(h)] = int(v)
    return 0
def atomic_fetch_add(h, delta):
    with _astra_atomic_lock:
        key = int(h)
        old = int(_astra_atomics.get(key, 0))
        _astra_atomics[key] = old + int(delta)
    return old
def atomic_compare_exchange(h, expected, desired):
    with _astra_atomic_lock:
        key = int(h)
        cur = int(_astra_atomics.get(key, 0))
        if cur == int(expected):
            _astra_atomics[key] = int(desired)
            return True
    return False
def mutex_new():
    global _astra_next_mutex
    mid = _astra_next_mutex
    _astra_next_mutex += 1
    _astra_mutexes[mid] = threading.Lock()
    return mid
def mutex_lock(mid, owner_tid):
    lk = _astra_mutexes.get(int(mid))
    if lk is None:
        return 1
    lk.acquire()
    return 0
def mutex_unlock(mid, owner_tid):
    lk = _astra_mutexes.get(int(mid))
    if lk is None:
        return 1
    try:
        lk.release()
        return 0
    except RuntimeError:
        return 1
def chan_new():
    global _astra_next_chan
    cid = _astra_next_chan
    _astra_next_chan += 1
    cv = threading.Condition()
    _astra_channels[cid] = {'q': collections.deque(), 'closed': False, 'cv': cv}
    return cid
def chan_send(cid, v):
    ch = _astra_channels.get(int(cid))
    if ch is None:
        return 1
    cv = ch['cv']
    with cv:
        if ch['closed']:
            return 1
        ch['q'].append(v)
        cv.notify(1)
    return 0
def chan_recv_try(cid):
    ch = _astra_channels.get(int(cid))
    if ch is None:
        return None
    cv = ch['cv']
    with cv:
        if ch['q']:
            return ch['q'].popleft()
        return None
def chan_recv_blocking(cid):
    ch = _astra_channels.get(int(cid))
    if ch is None:
        return None
    cv = ch['cv']
    with cv:
        while not ch['q'] and not ch['closed']:
            cv.wait()
        if ch['q']:
            return ch['q'].popleft()
        return None
def chan_close(cid):
    ch = _astra_channels.get(int(cid))
    if ch is None:
        return 1
    cv = ch['cv']
    with cv:
        ch['closed'] = True
        cv.notify_all()
    return 0
def list_new(): return []
def list_push(xs, v): xs.append(v); return 0
def list_get(xs, i): return xs[int(i)]
def list_set(xs, i, v): xs[int(i)] = v; return 0
def list_len(xs): return len(xs)
def vec_new(): return []
def vec_from(xs): return list(xs)
def vec_len(xs): return len(xs)
def vec_get(xs, i):
    ii = int(i)
    return xs[ii] if 0 <= ii < len(xs) else None
def vec_set(xs, i, v): xs[int(i)] = v; return 0
def vec_push(xs, v): xs.append(v); return 0
def map_new(): return {}
def map_has(m, k): return k in m
def map_get(m, k): return m.get(k)
def map_set(m, k, v): m[k] = v; return 0
def file_exists(p): return pathlib.Path(p).exists()
def file_remove(p):
    try:
        pathlib.Path(p).unlink()
        return 0
    except FileNotFoundError:
        return 1
def _sock_new(s):
    global _astra_next_sock
    sid = _astra_next_sock
    _astra_next_sock += 1
    _astra_sockets[sid] = s
    return sid
def tcp_connect(addr):
    try:
        host, port = str(addr).rsplit(':', 1)
        s = socket.create_connection((host, int(port)), timeout=5.0)
        return _sock_new(s)
    except Exception:
        return -1
def tcp_send(sid, data):
    s = _astra_sockets.get(int(sid))
    if s is None: return -1
    try:
        return s.send(str(data).encode())
    except Exception:
        return -1
def tcp_recv(sid, n):
    s = _astra_sockets.get(int(sid))
    if s is None: return ''
    try:
        return s.recv(max(1, int(n))).decode(errors='replace')
    except Exception:
        return ''
def tcp_close(sid):
    s = _astra_sockets.pop(int(sid), None)
    if s is None: return 0
    try:
        s.close()
    except Exception:
        return -1
    return 0
def to_json(v): return json.dumps(v, sort_keys=True)
def from_json(s): return json.loads(s)
def sha256(s): return hashlib.sha256(str(s).encode()).hexdigest()
def hmac_sha256(k, s): return hmac.new(str(k).encode(), str(s).encode(), hashlib.sha256).hexdigest()
def rand_bytes(n):
    n = int(n)
    if n < 0:
        return None
    return list(os.urandom(n))
def proc_exit(code): raise SystemExit(int(code))
def panic(msg): import sys; print(f'panic: {msg}', file=sys.stderr); sys.exit(101)
def env_get(k): return os.environ.get(str(k), '')
def cwd(): return os.getcwd()
def proc_run(cmd): return subprocess.call(str(cmd), shell=True)
def now_unix(): return int(time.time())
def monotonic_ms(): return int(time.monotonic() * 1000)
def sleep_ms(ms): time.sleep(max(0, int(ms)) / 1000.0); return 0
def astra_str_concat(a, b): return str(a) + str(b)
def countOnes(x, bits=64):
    width = max(1, int(bits))
    v = int(x) & ((1 << width) - 1)
    return v.bit_count()
def leadingZeros(x, bits=64):
    width = max(1, int(bits))
    v = int(x) & ((1 << width) - 1)
    if v == 0: return width
    return max(0, width - v.bit_length())
def trailingZeros(x, bits=64):
    width = max(1, int(bits))
    v = int(x) & ((1 << width) - 1)
    if v == 0: return width
    tz = 0
    while (v & 1) == 0:
        v >>= 1
        tz += 1
    return tz
def popcnt(x, bits=64): return countOnes(x, bits)
def clz(x, bits=64): return leadingZeros(x, bits)
def ctz(x, bits=64): return trailingZeros(x, bits)
def rotl(x, n, bits=64):
    width = max(1, int(bits))
    mask = (1 << width) - 1
    v = int(x) & mask
    k = int(n) % width
    return ((v << k) | (v >> ((width - k) % width))) & mask
def rotr(x, n, bits=64):
    width = max(1, int(bits))
    mask = (1 << width) - 1
    v = int(x) & mask
    k = int(n) % width
    return ((v >> k) | (v << ((width - k) % width))) & mask
_astra_gpu_runtime.register_ir({'kernels': []}) if _astra_gpu_runtime is not None else None
class _AstraGpuNamespace:
    def __init__(self, runtime):
        self._runtime = runtime
    def available(self):
        return self._runtime.available()
    def device_count(self):
        return self._runtime.device_count()
    def device_name(self, index):
        return self._runtime.device_name(index)
    def alloc(self, size):
        return self._runtime.alloc(size)
    def copy(self, host_values):
        return self._runtime.copy(host_values)
    def read(self, memory):
        return self._runtime.read(memory)
    def launch(self, kernel, grid_size, block_size, *args):
        return self._runtime.launch(kernel, grid_size, block_size, *args)
    def global_id(self):
        return self._runtime.global_id()
    def thread_id(self):
        return self._runtime.thread_id()
    def block_id(self):
        return self._runtime.block_id()
    def block_dim(self):
        return self._runtime.block_dim()
    def grid_dim(self):
        return self._runtime.grid_dim()
    def barrier(self):
        return self._runtime.barrier()
gpu = _AstraGpuNamespace(_astra_gpu_runtime)
_astra_host_list_new = list_new
_astra_host_list_push = list_push
_astra_host_list_get = list_get
_astra_host_list_set = list_set
_astra_host_list_len = list_len
_astra_host_vec_new = vec_new
_astra_host_vec_from = vec_from
_astra_host_vec_len = vec_len
_astra_host_vec_get = vec_get
_astra_host_vec_set = vec_set
_astra_host_vec_push = vec_push
_astra_host_map_new = map_new
_astra_host_map_has = map_has
_astra_host_map_get = map_get
_astra_host_map_set = map_set
_astra_host_file_exists = file_exists
_astra_host_file_remove = file_remove
_astra_host_tcp_connect = tcp_connect
_astra_host_tcp_send = tcp_send
_astra_host_tcp_recv = tcp_recv
_astra_host_tcp_close = tcp_close
_astra_host_to_json = to_json
_astra_host_from_json = from_json
_astra_host_sha256 = sha256
_astra_host_hmac_sha256 = hmac_sha256
_astra_host_rand_bytes = rand_bytes
_astra_host_proc_exit = proc_exit
_astra_host_env_get = env_get
_astra_host_cwd = cwd
_astra_host_proc_run = proc_run
_astra_host_now_unix = now_unix
_astra_host_monotonic_ms = monotonic_ms
_astra_host_sleep_ms = sleep_ms
_astra_host_countOnes = countOnes
_astra_host_leadingZeros = leadingZeros
_astra_host_trailingZeros = trailingZeros
_astra_host_popcnt = popcnt
_astra_host_clz = clz
_astra_host_ctz = ctz
_astra_host_rotl = rotl
_astra_host_rotr = rotr
_astra_host_atomic_int_new = atomic_int_new
_astra_host_atomic_load = atomic_load
_astra_host_atomic_store = atomic_store
_astra_host_atomic_fetch_add = atomic_fetch_add
_astra_host_atomic_compare_exchange = atomic_compare_exchange
_astra_host_mutex_new = mutex_new
_astra_host_mutex_lock = mutex_lock
_astra_host_mutex_unlock = mutex_unlock
_astra_host_chan_new = chan_new
_astra_host_chan_send = chan_send
_astra_host_chan_recv_try = chan_recv_try
_astra_host_chan_recv_blocking = chan_recv_blocking
_astra_host_chan_close = chan_close
def __list_new(): return _astra_host_list_new()
def __list_push(xs, v): return _astra_host_list_push(xs, v)
def __list_get(xs, i): return _astra_host_list_get(xs, i)
def __list_set(xs, i, v): return _astra_host_list_set(xs, i, v)
def __list_len(xs): return _astra_host_list_len(xs)
def __vec_new(): return _astra_host_vec_new()
def __vec_from(xs): return _astra_host_vec_from(xs)
def __vec_len(xs): return _astra_host_vec_len(xs)
def __vec_get(xs, i): return _astra_host_vec_get(xs, i)
def __vec_set(xs, i, v): return _astra_host_vec_set(xs, i, v)
def __vec_push(xs, v): return _astra_host_vec_push(xs, v)
def __map_new(): return _astra_host_map_new()
def __map_has(m, k): return _astra_host_map_has(m, k)
def __map_get(m, k): return _astra_host_map_get(m, k)
def __map_set(m, k, v): return _astra_host_map_set(m, k, v)
def __file_exists(p): return _astra_host_file_exists(p)
def __file_remove(p): return _astra_host_file_remove(p)
def __tcp_connect(addr): return _astra_host_tcp_connect(addr)
def __tcp_send(sid, data): return _astra_host_tcp_send(sid, data)
def __tcp_recv(sid, n): return _astra_host_tcp_recv(sid, n)
def __tcp_close(sid): return _astra_host_tcp_close(sid)
def __to_json(v): return _astra_host_to_json(v)
def __from_json(s): return _astra_host_from_json(s)
def __sha256(s): return _astra_host_sha256(s)
def __hmac_sha256(k, s): return _astra_host_hmac_sha256(k, s)
def __rand_bytes(n): return _astra_host_rand_bytes(n)
def __proc_exit(code): return _astra_host_proc_exit(code)
def __env_get(k): return _astra_host_env_get(k)
def __cwd(): return _astra_host_cwd()
def __proc_run(cmd): return _astra_host_proc_run(cmd)
def __now_unix(): return _astra_host_now_unix()
def __monotonic_ms(): return _astra_host_monotonic_ms()
def __sleep_ms(ms): return _astra_host_sleep_ms(ms)
def __countOnes(x, bits=64): return _astra_host_countOnes(x, bits)
def __leadingZeros(x, bits=64): return _astra_host_leadingZeros(x, bits)
def __trailingZeros(x, bits=64): return _astra_host_trailingZeros(x, bits)
def __popcnt(x, bits=64): return _astra_host_popcnt(x, bits)
def __clz(x, bits=64): return _astra_host_clz(x, bits)
def __ctz(x, bits=64): return _astra_host_ctz(x, bits)
def __rotl(x, n, bits=64): return _astra_host_rotl(x, n, bits)
def __rotr(x, n, bits=64): return _astra_host_rotr(x, n, bits)
def __atomic_int_new(v): return _astra_host_atomic_int_new(v)
def __atomic_load(h): return _astra_host_atomic_load(h)
def __atomic_store(h, v): return _astra_host_atomic_store(h, v)
def __atomic_fetch_add(h, delta): return _astra_host_atomic_fetch_add(h, delta)
def __atomic_compare_exchange(h, expected, desired): return _astra_host_atomic_compare_exchange(h, expected, desired)
def __mutex_new(): return _astra_host_mutex_new()
def __mutex_lock(mid, owner_tid): return _astra_host_mutex_lock(mid, owner_tid)
def __mutex_unlock(mid, owner_tid): return _astra_host_mutex_unlock(mid, owner_tid)
def __chan_new(): return _astra_host_chan_new()
def __chan_send(cid, v): return _astra_host_chan_send(cid, v)
def __chan_recv_try(cid): return _astra_host_chan_recv_try(cid)
def __chan_recv_blocking(cid): return _astra_host_chan_recv_blocking(cid)
def __chan_close(cid): return _astra_host_chan_close(cid)
def _astra_load_lib(name):
    if name in _astra_libs:
        return _astra_libs[name]
    if name == 'c':
        _astra_libs[name] = ctypes.CDLL(None)
        return _astra_libs[name]
    if sys.platform == 'win32':
        candidates = [f'{name}.dll', f'lib{name}.dll']
    elif sys.platform == 'darwin':
        candidates = [f'lib{name}.dylib', f'lib{name}.so']
    else:
        candidates = [f'lib{name}.so', f'lib{name}.so.0', f'lib{name}.so.1']
    for c in candidates:
        try:
            _astra_libs[name] = ctypes.CDLL(c)
            return _astra_libs[name]
        except OSError:
            continue
    raise OSError(f"ASTRA FFI: cannot find native library '{name}'")
def _astra_load_first_lib(names):
    last = None
    for n in names:
        try:
            return _astra_load_lib(n)
        except OSError as err:
            last = err
    if last is not None:
        raise last
    raise OSError('ASTRA FFI: no link libraries were provided')
class Stack:
    def __init__(self, data):
        self.data = data
    def __repr__(self):
        return f"Stack(data={self.data!r})"

class Queue:
    def __init__(self, data, head):
        self.data = data
        self.head = head
    def __repr__(self):
        return f"Queue(data={self.data!r}, head={self.head!r})"

class RingBuffer:
    def __init__(self, data, head, tail, capacity):
        self.data = data
        self.head = head
        self.tail = tail
        self.capacity = capacity
    def __repr__(self):
        return f"RingBuffer(data={self.data!r}, head={self.head!r}, tail={self.tail!r}, capacity={self.capacity!r})"

def __sqrt_impl(x):
    try:
        return math.sqrt(x)
    except (TypeError, ValueError):
        return 0.0

def __pow_impl(x, y):
    try:
        return math.pow(x, y)
    except (TypeError, ValueError):
        return 0.0

def __log_impl(x):
    try:
        return math.log(x)
    except (TypeError, ValueError):
        return 0.0

def __log10_impl(x):
    try:
        return math.log10(x)
    except (TypeError, ValueError):
        return 0.0

def __exp_impl(x):
    try:
        return math.exp(x)
    except (TypeError, ValueError):
        return 0.0

def __round_impl(x):
    try:
        return int(round(x))
    except (TypeError, ValueError):
        return 0

def __floor_impl(x):
    try:
        return int(math.floor(x))
    except (TypeError, ValueError):
        return 0

def __ceil_impl(x):
    try:
        return int(math.ceil(x))
    except (TypeError, ValueError):
        return 0

def __sin_impl(x):
    try:
        return math.sin(x)
    except (TypeError, ValueError):
        return 0.0

def __cos_impl(x):
    try:
        return math.cos(x)
    except (TypeError, ValueError):
        return 0.0

def __tan_impl(x):
    try:
        return math.tan(x)
    except (TypeError, ValueError):
        return 0.0

def __asin_impl(x):
    try:
        return math.asin(x)
    except (TypeError, ValueError):
        return 0.0

def __acos_impl(x):
    try:
        return math.acos(x)
    except (TypeError, ValueError):
        return 0.0

def __atan_impl(x):
    try:
        return math.atan(x)
    except (TypeError, ValueError):
        return 0.0

def __atan2_impl(y, x):
    try:
        return math.atan2(y, x)
    except (TypeError, ValueError):
        return 0.0

def __sinh_impl(x):
    try:
        return math.sinh(x)
    except (TypeError, ValueError):
        return 0.0

def __cosh_impl(x):
    try:
        return math.cosh(x)
    except (TypeError, ValueError):
        return 0.0

def __tanh_impl(x):
    try:
        return math.tanh(x)
    except (TypeError, ValueError):
        return 0.0

def __str_char_at_impl(s, index):
    try:
        return s[index] if index < len(s) else ''
    except (IndexError, TypeError):
        return ''

def __str_from_char_impl(c):
    try:
        return str(c) if c is not None else ''
    except (TypeError, ValueError):
        return ''

def __str_substring_impl(s, start, length):
    try:
        return s[start:start+length] if s is not None else ''
    except (TypeError, ValueError):
        return ''

def __str_to_upper_impl(s):
    try:
        return s.upper() if s is not None else ''
    except AttributeError:
        return str(s).upper() if s is not None else ''

def __str_to_lower_impl(s):
    try:
        return s.lower() if s is not None else ''
    except AttributeError:
        return str(s).lower() if s is not None else ''

def __str_trim_impl(s):
    try:
        return s.strip() if s is not None else ''
    except AttributeError:
        return str(s).strip() if s is not None else ''

def __str_find_impl(s, pattern):
    try:
        return s.find(pattern) if s is not None and pattern is not None else -1
    except (AttributeError, TypeError):
        return str(s).find(str(pattern)) if s is not None and pattern is not None else -1

def __str_replace_impl(s, pattern, replacement):
    try:
        return s.replace(pattern, replacement) if s is not None and pattern is not None and replacement is not None else s
    except (AttributeError, TypeError):
        return str(s).replace(str(pattern), str(replacement)) if s is not None and pattern is not None and replacement is not None else str(s) if s is not None else ''

def main():
    _astra_defer_stack = []
    try:
        print_('Testing enhanced standard library...')
        test_string_utilities()
        test_math_functions()
        print_('All tests completed!')
        return 0
    except _AstraTryNone:
        return None
    except _AstraTryResultErr as __astra_err:
        return __astra_result_err(__astra_err.value)
    finally:
        for _d in reversed(_astra_defer_stack):
            _d()
def test_string_utilities():
    _astra_defer_stack = []
    try:
        print_('Testing string utilities...')
        str_len = length('Hello, World!')
        print_(astra_str_concat('Length: ', to_string_int(str_len)))
        sub = substring('Hello, World!', 7, 5)
        print_(astra_str_concat('Substring: ', sub))
        starts = starts_with('Hello, World!', 'Hello')
        print_(astra_str_concat("Starts with 'Hello': ", to_string_bool(starts)))
        ends = ends_with('Hello, World!', 'World!')
        print_(astra_str_concat("Ends with 'World!': ", to_string_bool(ends)))
        upper = to_upper('Hello, World!')
        print_(astra_str_concat('Uppercase: ', upper))
        lower = to_lower('Hello, World!')
        print_(astra_str_concat('Lowercase: ', lower))
    except _AstraTryNone:
        return None
    except _AstraTryResultErr as __astra_err:
        return __astra_result_err(__astra_err.value)
    finally:
        for _d in reversed(_astra_defer_stack):
            _d()
def test_math_functions():
    _astra_defer_stack = []
    try:
        print_('Testing math functions...')
        print_(astra_str_concat('min_int(10, 3): ', to_string_int(min_int(10, 3))))
        print_(astra_str_concat('max_int(10, 3): ', to_string_int(max_int(10, 3))))
        print_(astra_str_concat('abs_int(-5): ', to_string_int(abs_int(-5))))
        print_(astra_str_concat('clamp_int(15, 0, 10): ', to_string_int(clamp_int(15, 0, 10))))
        print_(astra_str_concat('min_float(3.14159, 2.71828): ', to_string_float(min_float(3.14159, 2.71828))))
        print_(astra_str_concat('max_float(3.14159, 2.71828): ', to_string_float(max_float(3.14159, 2.71828))))
        print_(astra_str_concat('abs_float(-2.5): ', to_string_float(abs_float(-2.5))))
        angle = (PI / 4.0)
        sin_val = sin(angle)
        cos_val = cos(angle)
        print_(astra_str_concat('sin(π/4): ', to_string_float(sin_val)))
        print_(astra_str_concat('cos(π/4): ', to_string_float(cos_val)))
        print_(astra_str_concat('PI: ', to_string_float(PI)))
        print_(astra_str_concat('E: ', to_string_float(E)))
    except _AstraTryNone:
        return None
    except _AstraTryResultErr as __astra_err:
        return __astra_result_err(__astra_err.value)
    finally:
        for _d in reversed(_astra_defer_stack):
            _d()
def vec_to_string(vec):
    _astra_defer_stack = []
    try:
        result = '['
        i = 0
        first = True
        while (i < vec_len(vec)):
            val = vec_get(vec, i)
            if (val != None):
                if (not first):
                    result += ', '
                else:
                    first = False
                val_int = ((lambda __v: __v if __v is not None else 0)(__astra_cast(val, 'Int | none')))
                result += to_string_int(val_int)
            i += 1
        result += ']'
        return result
    except _AstraTryNone:
        return None
    except _AstraTryResultErr as __astra_err:
        return __astra_result_err(__astra_err.value)
    finally:
        for _d in reversed(_astra_defer_stack):
            _d()
def min_int(a, b):
    _astra_defer_stack = []
    try:
        if (a < b):
            return a
        return b
    except _AstraTryNone:
        return None
    except _AstraTryResultErr as __astra_err:
        return __astra_result_err(__astra_err.value)
    finally:
        for _d in reversed(_astra_defer_stack):
            _d()
def max_int(a, b):
    _astra_defer_stack = []
    try:
        if (a > b):
            return a
        return b
    except _AstraTryNone:
        return None
    except _AstraTryResultErr as __astra_err:
        return __astra_result_err(__astra_err.value)
    finally:
        for _d in reversed(_astra_defer_stack):
            _d()
def clamp_int(x, lo, hi):
    _astra_defer_stack = []
    try:
        if (x < lo):
            return lo
        if (x > hi):
            return hi
        return x
    except _AstraTryNone:
        return None
    except _AstraTryResultErr as __astra_err:
        return __astra_result_err(__astra_err.value)
    finally:
        for _d in reversed(_astra_defer_stack):
            _d()
def abs_int(x):
    _astra_defer_stack = []
    try:
        if (x < 0):
            return (-x)
        return x
    except _AstraTryNone:
        return None
    except _AstraTryResultErr as __astra_err:
        return __astra_result_err(__astra_err.value)
    finally:
        for _d in reversed(_astra_defer_stack):
            _d()
def pow_int(base, exp):
    _astra_defer_stack = []
    try:
        if (exp < 0):
            return None
        if (exp == 0):
            return 1
        if ((base == 0) and (exp == 0)):
            return None
        result = 1
        current = base
        remaining = exp
        while (remaining > 0):
            if ((remaining % 2) == 1):
                result = (result * current)
                if ((result / current) != result):
                    return None
            current = (current * current)
            if ((current / base) != current):
                return None
            remaining = (remaining / 2)
        return result
    except _AstraTryNone:
        return None
    except _AstraTryResultErr as __astra_err:
        return __astra_result_err(__astra_err.value)
    finally:
        for _d in reversed(_astra_defer_stack):
            _d()
def is_even(x):
    _astra_defer_stack = []
    try:
        return ((x % 2) == 0)
    except _AstraTryNone:
        return None
    except _AstraTryResultErr as __astra_err:
        return __astra_result_err(__astra_err.value)
    finally:
        for _d in reversed(_astra_defer_stack):
            _d()
def is_odd(x):
    _astra_defer_stack = []
    try:
        return ((x % 2) != 0)
    except _AstraTryNone:
        return None
    except _AstraTryResultErr as __astra_err:
        return __astra_result_err(__astra_err.value)
    finally:
        for _d in reversed(_astra_defer_stack):
            _d()
def sign_int(x):
    _astra_defer_stack = []
    try:
        if (x < 0):
            return -1
        if (x > 0):
            return 1
        return 0
    except _AstraTryNone:
        return None
    except _AstraTryResultErr as __astra_err:
        return __astra_result_err(__astra_err.value)
    finally:
        for _d in reversed(_astra_defer_stack):
            _d()
def min_float(a, b):
    _astra_defer_stack = []
    try:
        if (a < b):
            return a
        return b
    except _AstraTryNone:
        return None
    except _AstraTryResultErr as __astra_err:
        return __astra_result_err(__astra_err.value)
    finally:
        for _d in reversed(_astra_defer_stack):
            _d()
def max_float(a, b):
    _astra_defer_stack = []
    try:
        if (a > b):
            return a
        return b
    except _AstraTryNone:
        return None
    except _AstraTryResultErr as __astra_err:
        return __astra_result_err(__astra_err.value)
    finally:
        for _d in reversed(_astra_defer_stack):
            _d()
def clamp_float(x, lo, hi):
    _astra_defer_stack = []
    try:
        if (x < lo):
            return lo
        if (x > hi):
            return hi
        return x
    except _AstraTryNone:
        return None
    except _AstraTryResultErr as __astra_err:
        return __astra_result_err(__astra_err.value)
    finally:
        for _d in reversed(_astra_defer_stack):
            _d()
def abs_float(x):
    _astra_defer_stack = []
    try:
        if (x < 0.0):
            return (-x)
        return x
    except _AstraTryNone:
        return None
    except _AstraTryResultErr as __astra_err:
        return __astra_result_err(__astra_err.value)
    finally:
        for _d in reversed(_astra_defer_stack):
            _d()
def sqrt(x):
    _astra_defer_stack = []
    try:
        if (x < 0.0):
            return None
        return __sqrt_impl(x)
    except _AstraTryNone:
        return None
    except _AstraTryResultErr as __astra_err:
        return __astra_result_err(__astra_err.value)
    finally:
        for _d in reversed(_astra_defer_stack):
            _d()
def pow(x, y):
    _astra_defer_stack = []
    try:
        return __pow_impl(x, y)
    except _AstraTryNone:
        return None
    except _AstraTryResultErr as __astra_err:
        return __astra_result_err(__astra_err.value)
    finally:
        for _d in reversed(_astra_defer_stack):
            _d()
def log(x):
    _astra_defer_stack = []
    try:
        if (x <= 0.0):
            return None
        return __log_impl(x)
    except _AstraTryNone:
        return None
    except _AstraTryResultErr as __astra_err:
        return __astra_result_err(__astra_err.value)
    finally:
        for _d in reversed(_astra_defer_stack):
            _d()
def log10(x):
    _astra_defer_stack = []
    try:
        if (x <= 0.0):
            return None
        return __log10_impl(x)
    except _AstraTryNone:
        return None
    except _AstraTryResultErr as __astra_err:
        return __astra_result_err(__astra_err.value)
    finally:
        for _d in reversed(_astra_defer_stack):
            _d()
def exp(x):
    _astra_defer_stack = []
    try:
        return __exp_impl(x)
    except _AstraTryNone:
        return None
    except _AstraTryResultErr as __astra_err:
        return __astra_result_err(__astra_err.value)
    finally:
        for _d in reversed(_astra_defer_stack):
            _d()
def round(x):
    _astra_defer_stack = []
    try:
        return __round_impl(x)
    except _AstraTryNone:
        return None
    except _AstraTryResultErr as __astra_err:
        return __astra_result_err(__astra_err.value)
    finally:
        for _d in reversed(_astra_defer_stack):
            _d()
def floor(x):
    _astra_defer_stack = []
    try:
        return __floor_impl(x)
    except _AstraTryNone:
        return None
    except _AstraTryResultErr as __astra_err:
        return __astra_result_err(__astra_err.value)
    finally:
        for _d in reversed(_astra_defer_stack):
            _d()
def ceil(x):
    _astra_defer_stack = []
    try:
        return __ceil_impl(x)
    except _AstraTryNone:
        return None
    except _AstraTryResultErr as __astra_err:
        return __astra_result_err(__astra_err.value)
    finally:
        for _d in reversed(_astra_defer_stack):
            _d()
def sin(x):
    _astra_defer_stack = []
    try:
        return __sin_impl(x)
    except _AstraTryNone:
        return None
    except _AstraTryResultErr as __astra_err:
        return __astra_result_err(__astra_err.value)
    finally:
        for _d in reversed(_astra_defer_stack):
            _d()
def cos(x):
    _astra_defer_stack = []
    try:
        return __cos_impl(x)
    except _AstraTryNone:
        return None
    except _AstraTryResultErr as __astra_err:
        return __astra_result_err(__astra_err.value)
    finally:
        for _d in reversed(_astra_defer_stack):
            _d()
def tan(x):
    _astra_defer_stack = []
    try:
        return __tan_impl(x)
    except _AstraTryNone:
        return None
    except _AstraTryResultErr as __astra_err:
        return __astra_result_err(__astra_err.value)
    finally:
        for _d in reversed(_astra_defer_stack):
            _d()
def asin(x):
    _astra_defer_stack = []
    try:
        if ((x < -1.0) or (x > 1.0)):
            return None
        return __asin_impl(x)
    except _AstraTryNone:
        return None
    except _AstraTryResultErr as __astra_err:
        return __astra_result_err(__astra_err.value)
    finally:
        for _d in reversed(_astra_defer_stack):
            _d()
def acos(x):
    _astra_defer_stack = []
    try:
        if ((x < -1.0) or (x > 1.0)):
            return None
        return __acos_impl(x)
    except _AstraTryNone:
        return None
    except _AstraTryResultErr as __astra_err:
        return __astra_result_err(__astra_err.value)
    finally:
        for _d in reversed(_astra_defer_stack):
            _d()
def atan(x):
    _astra_defer_stack = []
    try:
        return __atan_impl(x)
    except _AstraTryNone:
        return None
    except _AstraTryResultErr as __astra_err:
        return __astra_result_err(__astra_err.value)
    finally:
        for _d in reversed(_astra_defer_stack):
            _d()
def atan2(y, x):
    _astra_defer_stack = []
    try:
        return __atan2_impl(y, x)
    except _AstraTryNone:
        return None
    except _AstraTryResultErr as __astra_err:
        return __astra_result_err(__astra_err.value)
    finally:
        for _d in reversed(_astra_defer_stack):
            _d()
def sinh(x):
    _astra_defer_stack = []
    try:
        return __sinh_impl(x)
    except _AstraTryNone:
        return None
    except _AstraTryResultErr as __astra_err:
        return __astra_result_err(__astra_err.value)
    finally:
        for _d in reversed(_astra_defer_stack):
            _d()
def cosh(x):
    _astra_defer_stack = []
    try:
        return __cosh_impl(x)
    except _AstraTryNone:
        return None
    except _AstraTryResultErr as __astra_err:
        return __astra_result_err(__astra_err.value)
    finally:
        for _d in reversed(_astra_defer_stack):
            _d()
def tanh(x):
    _astra_defer_stack = []
    try:
        return __tanh_impl(x)
    except _AstraTryNone:
        return None
    except _AstraTryResultErr as __astra_err:
        return __astra_result_err(__astra_err.value)
    finally:
        for _d in reversed(_astra_defer_stack):
            _d()
def mean_int(data):
    _astra_defer_stack = []
    try:
        n = vec_len(data)
        if (n == 0):
            return None
        sum = 0
        i = 0
        while (i < n):
            val = vec_get(data, i)
            if (val != None):
                sum += __astra_cast(val, 'Int')
            i += 1
        return (__astra_cast(sum, 'Float') / __astra_cast(n, 'Float'))
    except _AstraTryNone:
        return None
    except _AstraTryResultErr as __astra_err:
        return __astra_result_err(__astra_err.value)
    finally:
        for _d in reversed(_astra_defer_stack):
            _d()
def median_int(data):
    _astra_defer_stack = []
    try:
        n = vec_len(data)
        if (n == 0):
            return None
        sorted = __astra_cast(vec_new(), 'Vec<Int>')
        i = 0
        while (i < n):
            val = vec_get(data, i)
            if (val != None):
                vec_push(sorted, __astra_cast(val, 'Int'))
            i += 1
        bubble_sort_int(sorted)
        if ((n % 2) == 1):
            mid_val = vec_get(sorted, (n / 2))
            if (mid_val != None):
                return __astra_cast(__astra_cast(mid_val, 'Int | none'), 'Float')
            else:
                return None
        else:
            val1 = vec_get(sorted, ((n / 2) - 1))
            val2 = vec_get(sorted, (n / 2))
            if ((val1 != None) and (val2 != None)):
                return (__astra_cast((__astra_cast(val1, 'Int') + __astra_cast(val2, 'Int')), 'Float') / 2.0)
            else:
                return None
    except _AstraTryNone:
        return None
    except _AstraTryResultErr as __astra_err:
        return __astra_result_err(__astra_err.value)
    finally:
        for _d in reversed(_astra_defer_stack):
            _d()
def std_dev_int(data):
    _astra_defer_stack = []
    try:
        mean = mean_int(data)
        if (mean == None):
            return None
        n = vec_len(data)
        if (n == 0):
            return None
        sum_sq_diff = 0.0
        i = 0
        while (i < n):
            val = vec_get(data, i)
            if (val != None):
                diff = (__astra_cast(__astra_cast(val, 'Int'), 'Float') - __astra_cast(mean, 'Float'))
                sum_sq_diff += (diff * diff)
            i += 1
        variance = (sum_sq_diff / __astra_cast(n, 'Float'))
        return sqrt(variance)
    except _AstraTryNone:
        return None
    except _AstraTryResultErr as __astra_err:
        return __astra_result_err(__astra_err.value)
    finally:
        for _d in reversed(_astra_defer_stack):
            _d()
def degrees_to_radians(degrees):
    _astra_defer_stack = []
    try:
        return ((degrees * PI) / 180.0)
    except _AstraTryNone:
        return None
    except _AstraTryResultErr as __astra_err:
        return __astra_result_err(__astra_err.value)
    finally:
        for _d in reversed(_astra_defer_stack):
            _d()
def radians_to_degrees(radians):
    _astra_defer_stack = []
    try:
        return ((radians * 180.0) / PI)
    except _AstraTryNone:
        return None
    except _AstraTryResultErr as __astra_err:
        return __astra_result_err(__astra_err.value)
    finally:
        for _d in reversed(_astra_defer_stack):
            _d()
def approx_equal(a, b, tolerance):
    _astra_defer_stack = []
    try:
        return (abs_float((a - b)) <= tolerance)
    except _AstraTryNone:
        return None
    except _AstraTryResultErr as __astra_err:
        return __astra_result_err(__astra_err.value)
    finally:
        for _d in reversed(_astra_defer_stack):
            _d()
def lerp(a, b, t):
    _astra_defer_stack = []
    try:
        return (a + (t * (b - a)))
    except _AstraTryNone:
        return None
    except _AstraTryResultErr as __astra_err:
        return __astra_result_err(__astra_err.value)
    finally:
        for _d in reversed(_astra_defer_stack):
            _d()
def binary_search_int(data, target):
    _astra_defer_stack = []
    try:
        left = 0
        right = (vec_len(data) - 1)
        while (left <= right):
            mid = (left + ((right - left) / 2))
            mid_val_opt = vec_get(data, mid)
            if (mid_val_opt == None):
                return None
            mid_val = ((lambda __v: __v if __v is not None else __astra_cast(0, 'Int'))(__astra_cast(mid_val_opt, 'Int | none')))
            if (mid_val == target):
                return mid
            if (mid_val < target):
                left = (mid + 1)
            else:
                right = (mid - 1)
        return None
    except _AstraTryNone:
        return None
    except _AstraTryResultErr as __astra_err:
        return __astra_result_err(__astra_err.value)
    finally:
        for _d in reversed(_astra_defer_stack):
            _d()
def linear_search_int(data, target):
    _astra_defer_stack = []
    try:
        i = 0
        n = vec_len(data)
        while (i < n):
            val_opt = vec_get(data, i)
            if (val_opt == None):
                return None
            val = ((lambda __v: __v if __v is not None else __astra_cast(0, 'Int'))(__astra_cast(val_opt, 'Int | none')))
            if (val == target):
                return i
            i += 1
        return None
    except _AstraTryNone:
        return None
    except _AstraTryResultErr as __astra_err:
        return __astra_result_err(__astra_err.value)
    finally:
        for _d in reversed(_astra_defer_stack):
            _d()
def find_min_int(data):
    _astra_defer_stack = []
    try:
        n = vec_len(data)
        if (n == 0):
            return None
        first_opt = vec_get(data, 0)
        if (first_opt == None):
            return None
        min_val = ((lambda __v: __v if __v is not None else __astra_cast(0, 'Int'))(__astra_cast(first_opt, 'Int | none')))
        i = 1
        while (i < n):
            val_opt = vec_get(data, i)
            if (val_opt == None):
                return None
            val = ((lambda __v: __v if __v is not None else __astra_cast(0, 'Int'))(__astra_cast(val_opt, 'Int | none')))
            if (val < min_val):
                min_val = val
            i += 1
        return min_val
    except _AstraTryNone:
        return None
    except _AstraTryResultErr as __astra_err:
        return __astra_result_err(__astra_err.value)
    finally:
        for _d in reversed(_astra_defer_stack):
            _d()
def find_max_int(data):
    _astra_defer_stack = []
    try:
        n = vec_len(data)
        if (n == 0):
            return None
        first_opt = vec_get(data, 0)
        if (first_opt == None):
            return None
        max_val = ((lambda __v: __v if __v is not None else __astra_cast(0, 'Int'))(__astra_cast(first_opt, 'Int | none')))
        i = 1
        while (i < n):
            val_opt = vec_get(data, i)
            if (val_opt == None):
                return None
            val = ((lambda __v: __v if __v is not None else __astra_cast(0, 'Int'))(__astra_cast(val_opt, 'Int | none')))
            if (val > max_val):
                max_val = val
            i += 1
        return max_val
    except _AstraTryNone:
        return None
    except _AstraTryResultErr as __astra_err:
        return __astra_result_err(__astra_err.value)
    finally:
        for _d in reversed(_astra_defer_stack):
            _d()
def contains_int(data, target):
    _astra_defer_stack = []
    try:
        i = 0
        n = vec_len(data)
        while (i < n):
            val_opt = vec_get(data, i)
            if (val_opt == None):
                return False
            val = ((lambda __v: __v if __v is not None else __astra_cast(0, 'Int'))(__astra_cast(val_opt, 'Int | none')))
            if (val == target):
                return True
            i += 1
        return False
    except _AstraTryNone:
        return None
    except _AstraTryResultErr as __astra_err:
        return __astra_result_err(__astra_err.value)
    finally:
        for _d in reversed(_astra_defer_stack):
            _d()
def count_int(data, target):
    _astra_defer_stack = []
    try:
        count = 0
        i = 0
        n = vec_len(data)
        while (i < n):
            val_opt = vec_get(data, i)
            if (val_opt == None):
                return count
            val = ((lambda __v: __v if __v is not None else __astra_cast(0, 'Int'))(__astra_cast(val_opt, 'Int | none')))
            if (val == target):
                count += 1
            i += 1
        return count
    except _AstraTryNone:
        return None
    except _AstraTryResultErr as __astra_err:
        return __astra_result_err(__astra_err.value)
    finally:
        for _d in reversed(_astra_defer_stack):
            _d()
def bubble_sort_int(data):
    _astra_defer_stack = []
    try:
        n = vec_len(data)
        if (n <= 1):
            return None
        i = 0
        while (i < (n - 1)):
            j = 0
            while (j < ((n - i) - 1)):
                val1_opt = vec_get(data, j)
                val2_opt = vec_get(data, (j + 1))
                if ((val1_opt != None) and (val2_opt != None)):
                    val1 = ((lambda __v: __v if __v is not None else __astra_cast(0, 'Int'))(__astra_cast(val1_opt, 'Int | none')))
                    val2 = ((lambda __v: __v if __v is not None else __astra_cast(0, 'Int'))(__astra_cast(val2_opt, 'Int | none')))
                    if (val1 > val2):
                        vec_set(data, j, val2)
                        vec_set(data, (j + 1), val1)
                j += 1
            i += 1
    except _AstraTryNone:
        return None
    except _AstraTryResultErr as __astra_err:
        return __astra_result_err(__astra_err.value)
    finally:
        for _d in reversed(_astra_defer_stack):
            _d()
def selection_sort_int(data):
    _astra_defer_stack = []
    try:
        n = vec_len(data)
        if (n <= 1):
            return None
        i = 0
        while (i < (n - 1)):
            min_idx = i
            j = (i + 1)
            while (j < n):
                val1_opt = vec_get(data, j)
                val2_opt = vec_get(data, min_idx)
                if ((val1_opt != None) and (val2_opt != None)):
                    val1 = ((lambda __v: __v if __v is not None else __astra_cast(0, 'Int'))(__astra_cast(val1_opt, 'Int | none')))
                    val2 = ((lambda __v: __v if __v is not None else __astra_cast(0, 'Int'))(__astra_cast(val2_opt, 'Int | none')))
                    if (val1 < val2):
                        min_idx = j
                j += 1
            if (min_idx != i):
                val_i_opt = vec_get(data, i)
                val_min_opt = vec_get(data, min_idx)
                if ((val_i_opt != None) and (val_min_opt != None)):
                    val_i = ((lambda __v: __v if __v is not None else __astra_cast(0, 'Int'))(__astra_cast(val_i_opt, 'Int | none')))
                    val_min = ((lambda __v: __v if __v is not None else __astra_cast(0, 'Int'))(__astra_cast(val_min_opt, 'Int | none')))
                    vec_set(data, i, val_min)
                    vec_set(data, min_idx, val_i)
            i += 1
    except _AstraTryNone:
        return None
    except _AstraTryResultErr as __astra_err:
        return __astra_result_err(__astra_err.value)
    finally:
        for _d in reversed(_astra_defer_stack):
            _d()
def insertion_sort_int(data):
    _astra_defer_stack = []
    try:
        n = vec_len(data)
        if (n <= 1):
            return None
        i = 1
        while (i < n):
            key_opt = vec_get(data, i)
            if (key_opt == None):
                i += 1
                continue
            key = ((lambda __v: __v if __v is not None else __astra_cast(0, 'Int'))(__astra_cast(key_opt, 'Int | none')))
            j = (i - 1)
            while (j >= 0):
                val_opt = vec_get(data, j)
                if (val_opt == None):
                    j -= 1
                    continue
                val = ((lambda __v: __v if __v is not None else __astra_cast(0, 'Int'))(__astra_cast(val_opt, 'Int | none')))
                if (val > key):
                    vec_set(data, (j + 1), val)
                    j -= 1
                else:
                    break
            vec_set(data, (j + 1), key)
            i += 1
    except _AstraTryNone:
        return None
    except _AstraTryResultErr as __astra_err:
        return __astra_result_err(__astra_err.value)
    finally:
        for _d in reversed(_astra_defer_stack):
            _d()
def quick_sort_partition_int(data, low, high):
    _astra_defer_stack = []
    try:
        pivot_opt = vec_get(data, high)
        if (pivot_opt == None):
            return low
        pivot = ((lambda __v: __v if __v is not None else __astra_cast(0, 'Int'))(__astra_cast(pivot_opt, 'Int | none')))
        i = (low - 1)
        j = low
        while (j < high):
            val_opt = vec_get(data, j)
            if (val_opt == None):
                j += 1
                continue
            val = ((lambda __v: __v if __v is not None else __astra_cast(0, 'Int'))(__astra_cast(val_opt, 'Int | none')))
            if (val <= pivot):
                i += 1
                val_i_opt = vec_get(data, i)
                if (val_i_opt != None):
                    val_i = ((lambda __v: __v if __v is not None else __astra_cast(0, 'Int'))(__astra_cast(val_i_opt, 'Int | none')))
                    vec_set(data, i, val)
                    vec_set(data, j, val_i)
            j += 1
        val_i_opt = vec_get(data, (i + 1))
        if (val_i_opt != None):
            val_i = ((lambda __v: __v if __v is not None else __astra_cast(0, 'Int'))(__astra_cast(val_i_opt, 'Int | none')))
            vec_set(data, (i + 1), pivot)
            vec_set(data, high, val_i)
        return (i + 1)
    except _AstraTryNone:
        return None
    except _AstraTryResultErr as __astra_err:
        return __astra_result_err(__astra_err.value)
    finally:
        for _d in reversed(_astra_defer_stack):
            _d()
def quick_sort_helper_int(data, low, high):
    _astra_defer_stack = []
    try:
        if (low < high):
            pi = quick_sort_partition_int(data, low, high)
            quick_sort_helper_int(data, low, (pi - 1))
            quick_sort_helper_int(data, (pi + 1), high)
    except _AstraTryNone:
        return None
    except _AstraTryResultErr as __astra_err:
        return __astra_result_err(__astra_err.value)
    finally:
        for _d in reversed(_astra_defer_stack):
            _d()
def quick_sort_int(data):
    _astra_defer_stack = []
    try:
        n = vec_len(data)
        if (n <= 1):
            return None
        quick_sort_helper_int(data, 0, (n - 1))
    except _AstraTryNone:
        return None
    except _AstraTryResultErr as __astra_err:
        return __astra_result_err(__astra_err.value)
    finally:
        for _d in reversed(_astra_defer_stack):
            _d()
def stack_new():
    _astra_defer_stack = []
    try:
        return Stack(__astra_cast(vec_new(), 'Vec<Any>'))
    except _AstraTryNone:
        return None
    except _AstraTryResultErr as __astra_err:
        return __astra_result_err(__astra_err.value)
    finally:
        for _d in reversed(_astra_defer_stack):
            _d()
def stack_push(stack, value):
    _astra_defer_stack = []
    try:
        vec_push((stack).data, value)
    except _AstraTryNone:
        return None
    except _AstraTryResultErr as __astra_err:
        return __astra_result_err(__astra_err.value)
    finally:
        for _d in reversed(_astra_defer_stack):
            _d()
def stack_pop(stack):
    _astra_defer_stack = []
    try:
        n = vec_len((stack).data)
        if (n == 0):
            return None
        result = vec_get((stack).data, (n - 1))
        return result
    except _AstraTryNone:
        return None
    except _AstraTryResultErr as __astra_err:
        return __astra_result_err(__astra_err.value)
    finally:
        for _d in reversed(_astra_defer_stack):
            _d()
def stack_peek(stack):
    _astra_defer_stack = []
    try:
        n = vec_len((stack).data)
        if (n == 0):
            return None
        return ((stack).data)[(n - 1)]
    except _AstraTryNone:
        return None
    except _AstraTryResultErr as __astra_err:
        return __astra_result_err(__astra_err.value)
    finally:
        for _d in reversed(_astra_defer_stack):
            _d()
def stack_is_empty(stack):
    _astra_defer_stack = []
    try:
        return (vec_len((stack).data) == 0)
    except _AstraTryNone:
        return None
    except _AstraTryResultErr as __astra_err:
        return __astra_result_err(__astra_err.value)
    finally:
        for _d in reversed(_astra_defer_stack):
            _d()
def stack_size(stack):
    _astra_defer_stack = []
    try:
        return vec_len((stack).data)
    except _AstraTryNone:
        return None
    except _AstraTryResultErr as __astra_err:
        return __astra_result_err(__astra_err.value)
    finally:
        for _d in reversed(_astra_defer_stack):
            _d()
def queue_new():
    _astra_defer_stack = []
    try:
        return Queue(__astra_cast(vec_new(), 'Vec<Any>'), 0)
    except _AstraTryNone:
        return None
    except _AstraTryResultErr as __astra_err:
        return __astra_result_err(__astra_err.value)
    finally:
        for _d in reversed(_astra_defer_stack):
            _d()
def queue_enqueue(queue, value):
    _astra_defer_stack = []
    try:
        vec_push((queue).data, value)
    except _AstraTryNone:
        return None
    except _AstraTryResultErr as __astra_err:
        return __astra_result_err(__astra_err.value)
    finally:
        for _d in reversed(_astra_defer_stack):
            _d()
def queue_dequeue(queue):
    _astra_defer_stack = []
    try:
        if ((queue).head >= vec_len((queue).data)):
            return None
        result = ((queue).data)[(queue).head]
        (queue).head += 1
        return result
    except _AstraTryNone:
        return None
    except _AstraTryResultErr as __astra_err:
        return __astra_result_err(__astra_err.value)
    finally:
        for _d in reversed(_astra_defer_stack):
            _d()
def queue_peek(queue):
    _astra_defer_stack = []
    try:
        if ((queue).head >= vec_len((queue).data)):
            return None
        return ((queue).data)[(queue).head]
    except _AstraTryNone:
        return None
    except _AstraTryResultErr as __astra_err:
        return __astra_result_err(__astra_err.value)
    finally:
        for _d in reversed(_astra_defer_stack):
            _d()
def queue_is_empty(queue):
    _astra_defer_stack = []
    try:
        return ((queue).head >= vec_len((queue).data))
    except _AstraTryNone:
        return None
    except _AstraTryResultErr as __astra_err:
        return __astra_result_err(__astra_err.value)
    finally:
        for _d in reversed(_astra_defer_stack):
            _d()
def queue_size(queue):
    _astra_defer_stack = []
    try:
        return (vec_len((queue).data) - (queue).head)
    except _AstraTryNone:
        return None
    except _AstraTryResultErr as __astra_err:
        return __astra_result_err(__astra_err.value)
    finally:
        for _d in reversed(_astra_defer_stack):
            _d()
def queue_compact(queue):
    _astra_defer_stack = []
    try:
        if ((queue).head > 0):
            new_data = __astra_cast(vec_new(), 'Vec<Any>')
            i = (queue).head
            while (i < vec_len((queue).data)):
                item = vec_get((queue).data, i)
                if (item != None):
                    vec_push(new_data, item)
                i += 1
            (queue).data = new_data
            (queue).head = 0
    except _AstraTryNone:
        return None
    except _AstraTryResultErr as __astra_err:
        return __astra_result_err(__astra_err.value)
    finally:
        for _d in reversed(_astra_defer_stack):
            _d()
def ring_buffer_new(capacity):
    _astra_defer_stack = []
    try:
        if (capacity <= 0):
            capacity = 1
        data = __astra_cast(vec_new(), 'Vec<Any>')
        i = 0
        while (i < capacity):
            vec_push(data, __astra_cast(0, 'Any'))
            i += 1
        return RingBuffer(data, 0, 0, capacity)
    except _AstraTryNone:
        return None
    except _AstraTryResultErr as __astra_err:
        return __astra_result_err(__astra_err.value)
    finally:
        for _d in reversed(_astra_defer_stack):
            _d()
def ring_buffer_push(buffer, value):
    _astra_defer_stack = []
    try:
        next_tail = (((buffer).tail + 1) % (buffer).capacity)
        if (next_tail == (buffer).head):
            return None
        ((buffer).data)[(buffer).tail] = value
        (buffer).tail = next_tail
        return True
    except _AstraTryNone:
        return None
    except _AstraTryResultErr as __astra_err:
        return __astra_result_err(__astra_err.value)
    finally:
        for _d in reversed(_astra_defer_stack):
            _d()
def ring_buffer_pop(buffer):
    _astra_defer_stack = []
    try:
        if ((buffer).head == (buffer).tail):
            return None
        result = ((buffer).data)[(buffer).head]
        (buffer).head = (((buffer).head + 1) % (buffer).capacity)
        return result
    except _AstraTryNone:
        return None
    except _AstraTryResultErr as __astra_err:
        return __astra_result_err(__astra_err.value)
    finally:
        for _d in reversed(_astra_defer_stack):
            _d()
def length(s):
    _astra_defer_stack = []
    try:
        return len_(s)
    except _AstraTryNone:
        return None
    except _AstraTryResultErr as __astra_err:
        return __astra_result_err(__astra_err.value)
    finally:
        for _d in reversed(_astra_defer_stack):
            _d()
def is_empty(s):
    _astra_defer_stack = []
    try:
        return (len_(s) == 0)
    except _AstraTryNone:
        return None
    except _AstraTryResultErr as __astra_err:
        return __astra_result_err(__astra_err.value)
    finally:
        for _d in reversed(_astra_defer_stack):
            _d()
def to_string_int(x):
    _astra_defer_stack = []
    try:
        return __to_json(x)
    except _AstraTryNone:
        return None
    except _AstraTryResultErr as __astra_err:
        return __astra_result_err(__astra_err.value)
    finally:
        for _d in reversed(_astra_defer_stack):
            _d()
def to_string_bool(x):
    _astra_defer_stack = []
    try:
        return __to_json(x)
    except _AstraTryNone:
        return None
    except _AstraTryResultErr as __astra_err:
        return __astra_result_err(__astra_err.value)
    finally:
        for _d in reversed(_astra_defer_stack):
            _d()
def to_string_float(x):
    _astra_defer_stack = []
    try:
        return __to_json(x)
    except _AstraTryNone:
        return None
    except _AstraTryResultErr as __astra_err:
        return __astra_result_err(__astra_err.value)
    finally:
        for _d in reversed(_astra_defer_stack):
            _d()
def parse_int(s):
    _astra_defer_stack = []
    try:
        return __astra_cast(__from_json(s), 'Int')
    except _AstraTryNone:
        return None
    except _AstraTryResultErr as __astra_err:
        return __astra_result_err(__astra_err.value)
    finally:
        for _d in reversed(_astra_defer_stack):
            _d()
def from_char(c):
    _astra_defer_stack = []
    try:
        return __str_from_char_impl(c)
    except _AstraTryNone:
        return None
    except _AstraTryResultErr as __astra_err:
        return __astra_result_err(__astra_err.value)
    finally:
        for _d in reversed(_astra_defer_stack):
            _d()
def substring(s, start, length):
    _astra_defer_stack = []
    try:
        if (((start < 0) or (length < 0)) or (start >= len_(s))):
            return ''
        end = (start + length)
        if (end > len_(s)):
            end = len_(s)
        return __str_substring_impl(s, start, (end - start))
    except _AstraTryNone:
        return None
    except _AstraTryResultErr as __astra_err:
        return __astra_result_err(__astra_err.value)
    finally:
        for _d in reversed(_astra_defer_stack):
            _d()
def starts_with(s, prefix):
    _astra_defer_stack = []
    try:
        if (len_(prefix) > len_(s)):
            return False
        return (substring(s, 0, len_(prefix)) == prefix)
    except _AstraTryNone:
        return None
    except _AstraTryResultErr as __astra_err:
        return __astra_result_err(__astra_err.value)
    finally:
        for _d in reversed(_astra_defer_stack):
            _d()
def ends_with(s, suffix):
    _astra_defer_stack = []
    try:
        if (len_(suffix) > len_(s)):
            return False
        start = (len_(s) - len_(suffix))
        return (substring(s, start, len_(suffix)) == suffix)
    except _AstraTryNone:
        return None
    except _AstraTryResultErr as __astra_err:
        return __astra_result_err(__astra_err.value)
    finally:
        for _d in reversed(_astra_defer_stack):
            _d()
def to_upper(s):
    _astra_defer_stack = []
    try:
        return __str_to_upper_impl(s)
    except _AstraTryNone:
        return None
    except _AstraTryResultErr as __astra_err:
        return __astra_result_err(__astra_err.value)
    finally:
        for _d in reversed(_astra_defer_stack):
            _d()
def to_lower(s):
    _astra_defer_stack = []
    try:
        return __str_to_lower_impl(s)
    except _AstraTryNone:
        return None
    except _AstraTryResultErr as __astra_err:
        return __astra_result_err(__astra_err.value)
    finally:
        for _d in reversed(_astra_defer_stack):
            _d()
def trim(s):
    _astra_defer_stack = []
    try:
        return __str_trim_impl(s)
    except _AstraTryNone:
        return None
    except _AstraTryResultErr as __astra_err:
        return __astra_result_err(__astra_err.value)
    finally:
        for _d in reversed(_astra_defer_stack):
            _d()
def find(s, pattern):
    _astra_defer_stack = []
    try:
        return __str_find_impl(s, pattern)
    except _AstraTryNone:
        return None
    except _AstraTryResultErr as __astra_err:
        return __astra_result_err(__astra_err.value)
    finally:
        for _d in reversed(_astra_defer_stack):
            _d()
def replace(s, pattern, replacement):
    _astra_defer_stack = []
    try:
        return __str_replace_impl(s, pattern, replacement)
    except _AstraTryNone:
        return None
    except _AstraTryResultErr as __astra_err:
        return __astra_result_err(__astra_err.value)
    finally:
        for _d in reversed(_astra_defer_stack):
            _d()
if __name__ == '__main__':
    _main_out = main()
    if inspect.isawaitable(_main_out):
        _main_out = asyncio.run(_main_out)
    raise SystemExit(_main_out if isinstance(_main_out, int) else 0)
