# generated by astra
import asyncio, collections, ctypes, hashlib, hmac, inspect, json, os, pathlib, socket, subprocess, sys, threading, time
_astra_gpu_runtime = _astra_gpu_get_runtime() if '_astra_gpu_get_runtime' in globals() else None
_astra_heap = {}
_astra_next_ptr = 1
_astra_threads = {}
_astra_next_tid = 1
_astra_atomics = {}
_astra_next_atomic = 1
_astra_atomic_lock = threading.Lock()
_astra_mutexes = {}
_astra_next_mutex = 1
_astra_channels = {}
_astra_next_chan = 1
_astra_sockets = {}
_astra_next_sock = 1
_astra_libs = {}
def __astra_cast(v, t):
    if t in ('Float', 'f32', 'f64'):
        return float(v)
    if t in ('Int', 'isize'): bits, signed = 64, True
    elif t == 'usize': bits, signed = 64, False
    elif t.startswith('i') and t[1:].isdigit(): bits, signed = int(t[1:]), True
    elif t.startswith('u') and t[1:].isdigit(): bits, signed = int(t[1:]), False
    else: return v
    if isinstance(v, float):
        if v != v: return 0
        if v == float('inf'):
            return (1 << (bits - 1)) - 1 if signed else (1 << bits) - 1
        if v == float('-inf'):
            return (-(1 << (bits - 1))) if signed else 0
        v = int(v)
    else:
        v = int(v)
    mask = (1 << bits) - 1
    out = v & mask
    if signed and out >= (1 << (bits - 1)):
        out -= (1 << bits)
    return out
def print_(*args): print(*args); return None
class _AstraTryNone(Exception):
    pass
class _AstraTryResultErr(Exception):
    def __init__(self, value):
        super().__init__('result-err')
        self.value = value
def __astra_result_err(v):
    return {'__enum__': 'Result', 'tag': 'Err', 'values': [v]}
def __astra_try_unwrap(v):
    if v is None:
        raise _AstraTryNone()
    return v
def __astra_try_unwrap_result(v):
    if isinstance(v, dict) and v.get('__enum__') == 'Result':
        tag = v.get('tag')
        vals = v.get('values')
        if not isinstance(vals, list):
            vals = []
        if tag == 'Ok':
            return vals[0] if vals else None
        if tag == 'Err':
            raise _AstraTryResultErr(vals[0] if vals else None)
    raise TypeError('`!` on Result expected Result.Ok/Result.Err value')
def len_(x): return len(x)
def read_file(p): return pathlib.Path(p).read_text()
def write_file(p,s): pathlib.Path(p).write_text(str(s)); return 0
def args(): return sys.argv
def arg(i): return sys.argv[i] if 0 <= int(i) < len(sys.argv) else ''
def alloc(n):
    global _astra_next_ptr
    ptr = _astra_next_ptr
    _astra_next_ptr += 1
    _astra_heap[ptr] = bytearray(max(0, int(n)))
    return ptr
def free(ptr):
    _astra_heap.pop(ptr, None)
    return None
def spawn(fn, *a):
    global _astra_next_tid
    tid = _astra_next_tid
    _astra_next_tid += 1
    state = {'done': False, 'result': 0, 'thread': None}
    def _runner():
        try:
            out = fn(*a)
            if inspect.isawaitable(out):
                out = asyncio.run(out)
            state['result'] = out
        except Exception:
            state['result'] = 0
        finally:
            state['done'] = True
    th = threading.Thread(target=_runner, daemon=False)
    state['thread'] = th
    _astra_threads[tid] = state
    th.start()
    return tid
def join(tid):
    state = _astra_threads.get(int(tid))
    if state is None:
        return 0
    th = state.get('thread')
    if th is not None:
        th.join()
    return state['result']
def await_result(v):
    if inspect.isawaitable(v):
        return asyncio.run(v)
    return v
def atomic_int_new(v):
    global _astra_next_atomic
    with _astra_atomic_lock:
        h = _astra_next_atomic
        _astra_next_atomic += 1
        _astra_atomics[h] = int(v)
    return h
def atomic_load(h):
    with _astra_atomic_lock:
        return int(_astra_atomics.get(int(h), 0))
def atomic_store(h, v):
    with _astra_atomic_lock:
        _astra_atomics[int(h)] = int(v)
    return 0
def atomic_fetch_add(h, delta):
    with _astra_atomic_lock:
        key = int(h)
        old = int(_astra_atomics.get(key, 0))
        _astra_atomics[key] = old + int(delta)
    return old
def atomic_compare_exchange(h, expected, desired):
    with _astra_atomic_lock:
        key = int(h)
        cur = int(_astra_atomics.get(key, 0))
        if cur == int(expected):
            _astra_atomics[key] = int(desired)
            return True
    return False
def mutex_new():
    global _astra_next_mutex
    mid = _astra_next_mutex
    _astra_next_mutex += 1
    _astra_mutexes[mid] = threading.Lock()
    return mid
def mutex_lock(mid, owner_tid):
    lk = _astra_mutexes.get(int(mid))
    if lk is None:
        return 1
    lk.acquire()
    return 0
def mutex_unlock(mid, owner_tid):
    lk = _astra_mutexes.get(int(mid))
    if lk is None:
        return 1
    try:
        lk.release()
        return 0
    except RuntimeError:
        return 1
def chan_new():
    global _astra_next_chan
    cid = _astra_next_chan
    _astra_next_chan += 1
    cv = threading.Condition()
    _astra_channels[cid] = {'q': collections.deque(), 'closed': False, 'cv': cv}
    return cid
def chan_send(cid, v):
    ch = _astra_channels.get(int(cid))
    if ch is None:
        return 1
    cv = ch['cv']
    with cv:
        if ch['closed']:
            return 1
        ch['q'].append(v)
        cv.notify(1)
    return 0
def chan_recv_try(cid):
    ch = _astra_channels.get(int(cid))
    if ch is None:
        return None
    cv = ch['cv']
    with cv:
        if ch['q']:
            return ch['q'].popleft()
        return None
def chan_recv_blocking(cid):
    ch = _astra_channels.get(int(cid))
    if ch is None:
        return None
    cv = ch['cv']
    with cv:
        while not ch['q'] and not ch['closed']:
            cv.wait()
        if ch['q']:
            return ch['q'].popleft()
        return None
def chan_close(cid):
    ch = _astra_channels.get(int(cid))
    if ch is None:
        return 1
    cv = ch['cv']
    with cv:
        ch['closed'] = True
        cv.notify_all()
    return 0
def list_new(): return []
def list_push(xs, v): xs.append(v); return 0
def list_get(xs, i): return xs[int(i)]
def list_set(xs, i, v): xs[int(i)] = v; return 0
def list_len(xs): return len(xs)
def vec_new(): return []
def vec_from(xs): return list(xs)
def vec_len(xs): return len(xs)
def vec_get(xs, i):
    ii = int(i)
    return xs[ii] if 0 <= ii < len(xs) else None
def vec_set(xs, i, v): xs[int(i)] = v; return 0
def vec_push(xs, v): xs.append(v); return 0
def map_new(): return {}
def map_has(m, k): return k in m
def map_get(m, k): return m.get(k)
def map_set(m, k, v): m[k] = v; return 0
def file_exists(p): return pathlib.Path(p).exists()
def file_remove(p):
    try:
        pathlib.Path(p).unlink()
        return 0
    except FileNotFoundError:
        return 1
def _sock_new(s):
    global _astra_next_sock
    sid = _astra_next_sock
    _astra_next_sock += 1
    _astra_sockets[sid] = s
    return sid
def tcp_connect(addr):
    try:
        host, port = str(addr).rsplit(':', 1)
        s = socket.create_connection((host, int(port)), timeout=5.0)
        return _sock_new(s)
    except Exception:
        return -1
def tcp_send(sid, data):
    s = _astra_sockets.get(int(sid))
    if s is None: return -1
    try:
        return s.send(str(data).encode())
    except Exception:
        return -1
def tcp_recv(sid, n):
    s = _astra_sockets.get(int(sid))
    if s is None: return ''
    try:
        return s.recv(max(1, int(n))).decode(errors='replace')
    except Exception:
        return ''
def tcp_close(sid):
    s = _astra_sockets.pop(int(sid), None)
    if s is None: return 0
    try:
        s.close()
    except Exception:
        return -1
    return 0
def to_json(v): return json.dumps(v, sort_keys=True)
def from_json(s): return json.loads(s)
def sha256(s): return hashlib.sha256(str(s).encode()).hexdigest()
def hmac_sha256(k, s): return hmac.new(str(k).encode(), str(s).encode(), hashlib.sha256).hexdigest()
def rand_bytes(n):
    n = int(n)
    if n < 0:
        return None
    return list(os.urandom(n))
def proc_exit(code): raise SystemExit(int(code))
def panic(msg): import sys; print(f'panic: {msg}', file=sys.stderr); sys.exit(101)
def env_get(k): return os.environ.get(str(k), '')
def cwd(): return os.getcwd()
def proc_run(cmd): return subprocess.call(str(cmd), shell=True)
def now_unix(): return int(time.time())
def monotonic_ms(): return int(time.monotonic() * 1000)
def sleep_ms(ms): time.sleep(max(0, int(ms)) / 1000.0); return 0
def astra_str_concat(a, b): return str(a) + str(b)
def countOnes(x, bits=64):
    width = max(1, int(bits))
    v = int(x) & ((1 << width) - 1)
    return v.bit_count()
def leadingZeros(x, bits=64):
    width = max(1, int(bits))
    v = int(x) & ((1 << width) - 1)
    if v == 0: return width
    return max(0, width - v.bit_length())
def trailingZeros(x, bits=64):
    width = max(1, int(bits))
    v = int(x) & ((1 << width) - 1)
    if v == 0: return width
    tz = 0
    while (v & 1) == 0:
        v >>= 1
        tz += 1
    return tz
def popcnt(x, bits=64): return countOnes(x, bits)
def clz(x, bits=64): return leadingZeros(x, bits)
def ctz(x, bits=64): return trailingZeros(x, bits)
def rotl(x, n, bits=64):
    width = max(1, int(bits))
    mask = (1 << width) - 1
    v = int(x) & mask
    k = int(n) % width
    return ((v << k) | (v >> ((width - k) % width))) & mask
def rotr(x, n, bits=64):
    width = max(1, int(bits))
    mask = (1 << width) - 1
    v = int(x) & mask
    k = int(n) % width
    return ((v >> k) | (v << ((width - k) % width))) & mask
_astra_gpu_runtime.register_ir({'kernels': []}) if _astra_gpu_runtime is not None else None
class _AstraGpuNamespace:
    def __init__(self, runtime):
        self._runtime = runtime
    def available(self):
        return self._runtime.available()
    def device_count(self):
        return self._runtime.device_count()
    def device_name(self, index):
        return self._runtime.device_name(index)
    def alloc(self, size):
        return self._runtime.alloc(size)
    def copy(self, host_values):
        return self._runtime.copy(host_values)
    def read(self, memory):
        return self._runtime.read(memory)
    def launch(self, kernel, grid_size, block_size, *args):
        return self._runtime.launch(kernel, grid_size, block_size, *args)
    def global_id(self):
        return self._runtime.global_id()
    def thread_id(self):
        return self._runtime.thread_id()
    def block_id(self):
        return self._runtime.block_id()
    def block_dim(self):
        return self._runtime.block_dim()
    def grid_dim(self):
        return self._runtime.grid_dim()
    def barrier(self):
        return self._runtime.barrier()
gpu = _AstraGpuNamespace(_astra_gpu_runtime)
_astra_host_list_new = list_new
_astra_host_list_push = list_push
_astra_host_list_get = list_get
_astra_host_list_set = list_set
_astra_host_list_len = list_len
_astra_host_vec_new = vec_new
_astra_host_vec_from = vec_from
_astra_host_vec_len = vec_len
_astra_host_vec_get = vec_get
_astra_host_vec_set = vec_set
_astra_host_vec_push = vec_push
_astra_host_map_new = map_new
_astra_host_map_has = map_has
_astra_host_map_get = map_get
_astra_host_map_set = map_set
_astra_host_file_exists = file_exists
_astra_host_file_remove = file_remove
_astra_host_tcp_connect = tcp_connect
_astra_host_tcp_send = tcp_send
_astra_host_tcp_recv = tcp_recv
_astra_host_tcp_close = tcp_close
_astra_host_to_json = to_json
_astra_host_from_json = from_json
_astra_host_sha256 = sha256
_astra_host_hmac_sha256 = hmac_sha256
_astra_host_rand_bytes = rand_bytes
_astra_host_proc_exit = proc_exit
_astra_host_env_get = env_get
_astra_host_cwd = cwd
_astra_host_proc_run = proc_run
_astra_host_now_unix = now_unix
_astra_host_monotonic_ms = monotonic_ms
_astra_host_sleep_ms = sleep_ms
_astra_host_countOnes = countOnes
_astra_host_leadingZeros = leadingZeros
_astra_host_trailingZeros = trailingZeros
_astra_host_popcnt = popcnt
_astra_host_clz = clz
_astra_host_ctz = ctz
_astra_host_rotl = rotl
_astra_host_rotr = rotr
_astra_host_atomic_int_new = atomic_int_new
_astra_host_atomic_load = atomic_load
_astra_host_atomic_store = atomic_store
_astra_host_atomic_fetch_add = atomic_fetch_add
_astra_host_atomic_compare_exchange = atomic_compare_exchange
_astra_host_mutex_new = mutex_new
_astra_host_mutex_lock = mutex_lock
_astra_host_mutex_unlock = mutex_unlock
_astra_host_chan_new = chan_new
_astra_host_chan_send = chan_send
_astra_host_chan_recv_try = chan_recv_try
_astra_host_chan_recv_blocking = chan_recv_blocking
_astra_host_chan_close = chan_close
def __list_new(): return _astra_host_list_new()
def __list_push(xs, v): return _astra_host_list_push(xs, v)
def __list_get(xs, i): return _astra_host_list_get(xs, i)
def __list_set(xs, i, v): return _astra_host_list_set(xs, i, v)
def __list_len(xs): return _astra_host_list_len(xs)
def __vec_new(): return _astra_host_vec_new()
def __vec_from(xs): return _astra_host_vec_from(xs)
def __vec_len(xs): return _astra_host_vec_len(xs)
def __vec_get(xs, i): return _astra_host_vec_get(xs, i)
def __vec_set(xs, i, v): return _astra_host_vec_set(xs, i, v)
def __vec_push(xs, v): return _astra_host_vec_push(xs, v)
def __map_new(): return _astra_host_map_new()
def __map_has(m, k): return _astra_host_map_has(m, k)
def __map_get(m, k): return _astra_host_map_get(m, k)
def __map_set(m, k, v): return _astra_host_map_set(m, k, v)
def __file_exists(p): return _astra_host_file_exists(p)
def __file_remove(p): return _astra_host_file_remove(p)
def __tcp_connect(addr): return _astra_host_tcp_connect(addr)
def __tcp_send(sid, data): return _astra_host_tcp_send(sid, data)
def __tcp_recv(sid, n): return _astra_host_tcp_recv(sid, n)
def __tcp_close(sid): return _astra_host_tcp_close(sid)
def __to_json(v): return _astra_host_to_json(v)
def __from_json(s): return _astra_host_from_json(s)
def __sha256(s): return _astra_host_sha256(s)
def __hmac_sha256(k, s): return _astra_host_hmac_sha256(k, s)
def __rand_bytes(n): return _astra_host_rand_bytes(n)
def __proc_exit(code): return _astra_host_proc_exit(code)
def __env_get(k): return _astra_host_env_get(k)
def __cwd(): return _astra_host_cwd()
def __proc_run(cmd): return _astra_host_proc_run(cmd)
def __now_unix(): return _astra_host_now_unix()
def __monotonic_ms(): return _astra_host_monotonic_ms()
def __sleep_ms(ms): return _astra_host_sleep_ms(ms)
def __countOnes(x, bits=64): return _astra_host_countOnes(x, bits)
def __leadingZeros(x, bits=64): return _astra_host_leadingZeros(x, bits)
def __trailingZeros(x, bits=64): return _astra_host_trailingZeros(x, bits)
def __popcnt(x, bits=64): return _astra_host_popcnt(x, bits)
def __clz(x, bits=64): return _astra_host_clz(x, bits)
def __ctz(x, bits=64): return _astra_host_ctz(x, bits)
def __rotl(x, n, bits=64): return _astra_host_rotl(x, n, bits)
def __rotr(x, n, bits=64): return _astra_host_rotr(x, n, bits)
def __atomic_int_new(v): return _astra_host_atomic_int_new(v)
def __atomic_load(h): return _astra_host_atomic_load(h)
def __atomic_store(h, v): return _astra_host_atomic_store(h, v)
def __atomic_fetch_add(h, delta): return _astra_host_atomic_fetch_add(h, delta)
def __atomic_compare_exchange(h, expected, desired): return _astra_host_atomic_compare_exchange(h, expected, desired)
def __mutex_new(): return _astra_host_mutex_new()
def __mutex_lock(mid, owner_tid): return _astra_host_mutex_lock(mid, owner_tid)
def __mutex_unlock(mid, owner_tid): return _astra_host_mutex_unlock(mid, owner_tid)
def __chan_new(): return _astra_host_chan_new()
def __chan_send(cid, v): return _astra_host_chan_send(cid, v)
def __chan_recv_try(cid): return _astra_host_chan_recv_try(cid)
def __chan_recv_blocking(cid): return _astra_host_chan_recv_blocking(cid)
def __chan_close(cid): return _astra_host_chan_close(cid)
def _astra_load_lib(name):
    if name in _astra_libs:
        return _astra_libs[name]
    if name == 'c':
        _astra_libs[name] = ctypes.CDLL(None)
        return _astra_libs[name]
    if sys.platform == 'win32':
        candidates = [f'{name}.dll', f'lib{name}.dll']
    elif sys.platform == 'darwin':
        candidates = [f'lib{name}.dylib', f'lib{name}.so']
    else:
        candidates = [f'lib{name}.so', f'lib{name}.so.0', f'lib{name}.so.1']
    for c in candidates:
        try:
            _astra_libs[name] = ctypes.CDLL(c)
            return _astra_libs[name]
        except OSError:
            continue
    raise OSError(f"ASTRA FFI: cannot find native library '{name}'")
def _astra_load_first_lib(names):
    last = None
    for n in names:
        try:
            return _astra_load_lib(n)
        except OSError as err:
            last = err
    if last is not None:
        raise last
    raise OSError('ASTRA FFI: no link libraries were provided')
def main():
    _astra_defer_stack = []
    try:
        name = 'World'
        age = 25
        print_('hello ' + name)
        print_('Age: ' + str(age))
        print_('Name: ' + name + ', Age: ' + str(age))
        x = 10
        y = 20
        print_('Sum: ' + str((x + y)))
        return 0
    except _AstraTryNone:
        return None
    except _AstraTryResultErr as __astra_err:
        return __astra_result_err(__astra_err.value)
    finally:
        for _d in reversed(_astra_defer_stack):
            _d()
if __name__ == '__main__':
    _main_out = main()
    if inspect.isawaitable(_main_out):
        _main_out = asyncio.run(_main_out)
    raise SystemExit(_main_out if isinstance(_main_out, int) else 0)
