from astra.ast import *

def to_python(prog: Program) -> str:
    lines = ["# generated by astra", "import sys, pathlib"]
    lines += [
        "def print_(x): print(x)",
        "def len_(x): return len(x)",
        "def read_file(p): return pathlib.Path(p).read_text()",
        "def write_file(p,s): pathlib.Path(p).write_text(str(s)); return 0",
        "def args(): return sys.argv",
        "def arg(i): return sys.argv[i]",
    ]
    for fn in prog.items:
        params = ", ".join(n for n,_ in fn.params)
        lines.append(f"def {fn.name}({params}):")
        if not fn.body: lines.append("    pass")
        for st in fn.body: lines.extend(_stmt_py(st, 1))
    lines.append("if __name__ == '__main__':")
    lines.append("    rc = main()")
    lines.append("    raise SystemExit(rc if isinstance(rc, int) else 0)")
    return "\n".join(lines) + "\n"

def to_x86_64(prog: Program) -> str:
    return """global _start
section .text
_start:
  mov rax, 60
  mov rdi, 0
  syscall
"""

def _expr(e):
    if isinstance(e, Literal): return repr(e.value)
    if isinstance(e, Name): return e.value
    if isinstance(e, Binary): return f"({_expr(e.left)} {e.op} {_expr(e.right)})"
    if isinstance(e, Call):
        name = {"print":"print_","len":"len_"}.get(e.fn,e.fn)
        return f"{name}({', '.join(_expr(a) for a in e.args)})"
    return "None"

def _stmt_py(st, ind):
    p = "    "*ind
    if isinstance(st, LetStmt): return [f"{p}{st.name} = {_expr(st.expr)}"]
    if isinstance(st, ReturnStmt): return [f"{p}return {_expr(st.expr) if st.expr else 'None'}"]
    if isinstance(st, ExprStmt): return [f"{p}{_expr(st.expr)}"]
    if isinstance(st, IfStmt):
        lines=[f"{p}if {_expr(st.cond)}:"]
        for s in st.then_body: lines.extend(_stmt_py(s, ind+1))
        if not st.then_body: lines.append(f"{'    '*(ind+1)}pass")
        if st.else_body:
            lines.append(f"{p}else:")
            for s in st.else_body: lines.extend(_stmt_py(s, ind+1))
        return lines
    if isinstance(st, WhileStmt):
        lines=[f"{p}while {_expr(st.cond)}:"]
        for s in st.body: lines.extend(_stmt_py(s, ind+1))
        if not st.body: lines.append(f"{'    '*(ind+1)}pass")
        return lines
    return [f"{p}pass"]
