from __future__ import annotations

from dataclasses import dataclass
from typing import Any

from astra.ast import *


class CodegenError(Exception):
    pass


def _diag(node: Any, msg: str) -> str:
    line = getattr(node, "line", 0)
    col = getattr(node, "col", 0)
    return f"CODEGEN <input>:{line}:{col}: {msg}"


BIN_OP_MAP = {"&&": "and", "||": "or"}


def to_python(prog: Program, freestanding: bool = False) -> str:
    main_entry = "main"
    for item in prog.items:
        if isinstance(item, FnDecl) and item.name == "main":
            main_entry = item.symbol or item.name
            break
    lines = [
        "# generated by astra",
        "import asyncio, ctypes, hashlib, hmac, inspect, json, os, pathlib, socket, subprocess, sys, threading, time",
    ]
    lines += [
        "_astra_heap = {}",
        "_astra_next_ptr = 1",
        "_astra_threads = {}",
        "_astra_next_tid = 1",
        "_astra_sockets = {}",
        "_astra_next_sock = 1",
        "_astra_libs = {}",
        "def print_(x): print(x); return 0",
        "def len_(x): return len(x)",
        "def read_file(p): return pathlib.Path(p).read_text()",
        "def write_file(p,s): pathlib.Path(p).write_text(str(s)); return 0",
        "def args(): return sys.argv",
        "def arg(i): return sys.argv[i] if 0 <= int(i) < len(sys.argv) else ''",
        "def alloc(n):",
        "    global _astra_next_ptr",
        "    ptr = _astra_next_ptr",
        "    _astra_next_ptr += 1",
        "    _astra_heap[ptr] = bytearray(max(0, int(n)))",
        "    return ptr",
        "def free(ptr):",
        "    _astra_heap.pop(ptr, None)",
        "    return 0",
        "def spawn(fn, *a):",
        "    global _astra_next_tid",
        "    tid = _astra_next_tid",
        "    _astra_next_tid += 1",
        "    state = {'done': False, 'result': 0}",
        "    def _run():",
        "        try:",
        "            out = fn(*a)",
        "            if inspect.isawaitable(out):",
        "                out = asyncio.run(out)",
        "            state['result'] = out",
        "        finally:",
        "            state['done'] = True",
        "    th = threading.Thread(target=_run, daemon=True)",
        "    state['thread'] = th",
        "    _astra_threads[tid] = state",
        "    th.start()",
        "    return tid",
        "def join(tid):",
        "    state = _astra_threads.get(tid)",
        "    if state is None:",
        "        return 0",
        "    state['thread'].join()",
        "    return state['result']",
        "def await_result(v):",
        "    if inspect.isawaitable(v):",
        "        return asyncio.run(v)",
        "    return v",
        "def list_new(): return []",
        "def list_push(xs, v): xs.append(v); return 0",
        "def list_get(xs, i): return xs[int(i)]",
        "def list_set(xs, i, v): xs[int(i)] = v; return 0",
        "def list_len(xs): return len(xs)",
        "def map_new(): return {}",
        "def map_has(m, k): return k in m",
        "def map_get(m, k): return m.get(k)",
        "def map_set(m, k, v): m[k] = v; return 0",
        "def file_exists(p): return pathlib.Path(p).exists()",
        "def file_remove(p):",
        "    try:",
        "        pathlib.Path(p).unlink()",
        "        return 0",
        "    except FileNotFoundError:",
        "        return 1",
        "def _sock_new(s):",
        "    global _astra_next_sock",
        "    sid = _astra_next_sock",
        "    _astra_next_sock += 1",
        "    _astra_sockets[sid] = s",
        "    return sid",
        "def tcp_connect(addr):",
        "    host, port = str(addr).rsplit(':', 1)",
        "    s = socket.create_connection((host, int(port)), timeout=5.0)",
        "    return _sock_new(s)",
        "def tcp_send(sid, data):",
        "    s = _astra_sockets.get(int(sid))",
        "    if s is None: return 1",
        "    return s.send(str(data).encode())",
        "def tcp_recv(sid, n):",
        "    s = _astra_sockets.get(int(sid))",
        "    if s is None: return ''",
        "    return s.recv(max(1, int(n))).decode(errors='replace')",
        "def tcp_close(sid):",
        "    s = _astra_sockets.pop(int(sid), None)",
        "    if s is None: return 1",
        "    s.close()",
        "    return 0",
        "def to_json(v): return json.dumps(v, sort_keys=True)",
        "def from_json(s): return json.loads(s)",
        "def sha256(s): return hashlib.sha256(str(s).encode()).hexdigest()",
        "def hmac_sha256(k, s): return hmac.new(str(k).encode(), str(s).encode(), hashlib.sha256).hexdigest()",
        "def proc_exit(code): return int(code)",
        "def env_get(k): return os.environ.get(str(k), '')",
        "def cwd(): return os.getcwd()",
        "def proc_run(cmd): return subprocess.call(str(cmd), shell=True)",
        "def now_unix(): return int(time.time())",
        "def monotonic_ms(): return int(time.monotonic() * 1000)",
        "def sleep_ms(ms): time.sleep(max(0, int(ms)) / 1000.0); return 0",
        "def __list_new(): return list_new()",
        "def __list_push(xs, v): return list_push(xs, v)",
        "def __list_get(xs, i): return list_get(xs, i)",
        "def __list_set(xs, i, v): return list_set(xs, i, v)",
        "def __list_len(xs): return list_len(xs)",
        "def __map_new(): return map_new()",
        "def __map_has(m, k): return map_has(m, k)",
        "def __map_get(m, k): return map_get(m, k)",
        "def __map_set(m, k, v): return map_set(m, k, v)",
        "def __file_exists(p): return file_exists(p)",
        "def __file_remove(p): return file_remove(p)",
        "def __tcp_connect(addr): return tcp_connect(addr)",
        "def __tcp_send(sid, data): return tcp_send(sid, data)",
        "def __tcp_recv(sid, n): return tcp_recv(sid, n)",
        "def __tcp_close(sid): return tcp_close(sid)",
        "def __to_json(v): return to_json(v)",
        "def __from_json(s): return from_json(s)",
        "def __sha256(s): return sha256(s)",
        "def __hmac_sha256(k, s): return hmac_sha256(k, s)",
        "def __proc_exit(code): return proc_exit(code)",
        "def __env_get(k): return env_get(k)",
        "def __cwd(): return cwd()",
        "def __proc_run(cmd): return proc_run(cmd)",
        "def __now_unix(): return now_unix()",
        "def __monotonic_ms(): return monotonic_ms()",
        "def __sleep_ms(ms): return sleep_ms(ms)",
        "def _astra_load_lib(name):",
        "    if name not in _astra_libs:",
        "        _astra_libs[name] = ctypes.CDLL(name)",
        "    return _astra_libs[name]",
    ]
    for item in prog.items:
        if isinstance(item, StructDecl):
            lines.extend(_emit_py_struct(item))
        if isinstance(item, EnumDecl):
            lines.extend(_emit_py_enum(item))
    for item in prog.items:
        if isinstance(item, ExternFnDecl):
            lines.extend(_emit_py_extern(item))
    for item in prog.items:
        if not isinstance(item, FnDecl):
            continue
        fn_name = item.symbol or item.name
        params = ", ".join(n for n, _ in item.params)
        if item.async_fn:
            lines.append(f"async def {fn_name}({params}):")
        else:
            lines.append(f"def {fn_name}({params}):")
        lines.append("    _astra_defer_stack = []")
        lines.append("    try:")
        if not item.body:
            lines.append("        pass")
        for st in item.body:
            lines.extend(_stmt_py(st, 2))
        lines.append("    finally:")
        lines.append("        for _d in reversed(_astra_defer_stack):")
        lines.append("            _d()")
    if not freestanding:
        lines.append("if __name__ == '__main__':")
        lines.append(f"    _main_out = {main_entry}()")
        lines.append("    if inspect.isawaitable(_main_out):")
        lines.append("        _main_out = asyncio.run(_main_out)")
        lines.append("    raise SystemExit(_main_out if isinstance(_main_out, int) else 0)")
    return "\n".join(lines) + "\n"


def _emit_py_struct(item: StructDecl) -> list[str]:
    lines = [f"class {item.name}:"]
    fields = [n for n, _ in item.fields]
    args = ", ".join(fields)
    lines.append(f"    def __init__(self, {args}):" if args else "    def __init__(self):")
    if fields:
        for f in fields:
            lines.append(f"        self.{f} = {f}")
    else:
        lines.append("        pass")
    lines.append("    def __repr__(self):")
    if fields:
        fmt = ", ".join(f"{f}={{self.{f}!r}}" for f in fields)
        lines.append(f"        return f\"{item.name}({fmt})\"")
    else:
        lines.append(f"        return '{item.name}()'")
    lines.append("")
    return lines


def _emit_py_enum(item: EnumDecl) -> list[str]:
    lines: list[str] = [f"class {item.name}:"]
    if not item.variants:
        lines.append("    pass")
    for variant, vtypes in item.variants:
        if vtypes:
            lines.append("    @staticmethod")
            lines.append(f"    def {variant}(*values):")
            lines.append(f"        return {{'__enum__': '{item.name}', 'tag': '{variant}', 'values': list(values)}}")
        else:
            lines.append(f"    {variant} = {{'__enum__': '{item.name}', 'tag': '{variant}', 'values': []}}")
    lines.append("")
    return lines


def _emit_py_extern(item: ExternFnDecl) -> list[str]:
    args = ", ".join(n for n, _ in item.params)
    lines = [f"def {item.name}({args}):"]
    lines.append(f"    _lib = _astra_load_lib({item.lib!r})")
    lines.append(f"    _fn = getattr(_lib, {item.name!r})")
    call_args: list[str] = []
    for i, (name, typ) in enumerate(item.params):
        if typ == "String":
            lines.append(f"    _s{i} = str({name}).encode()")
            call_args.extend([f"_s{i}", f"len(_s{i})"])
        else:
            call_args.append(name)
    if item.ret == "Int":
        lines.append("    _fn.restype = ctypes.c_longlong")
    elif item.ret == "Bool":
        lines.append("    _fn.restype = ctypes.c_int")
    elif item.ret == "String":
        lines.append("    _fn.restype = ctypes.c_char_p")
    lines.append(f"    _ret = _fn({', '.join(call_args)})")
    if item.ret == "String":
        lines.append("    return _ret.decode() if _ret is not None else ''")
    elif item.ret == "Bool":
        lines.append("    return bool(_ret)")
    else:
        lines.append("    return _ret")
    lines.append("")
    return lines


def _call_name(fn: Any) -> str:
    if isinstance(fn, Name):
        return fn.value
    if isinstance(fn, str):
        return fn
    return _expr(fn)


def _expr(e):
    if isinstance(e, BoolLit):
        return "True" if e.value else "False"
    if isinstance(e, NilLit):
        return "None"
    if isinstance(e, Literal):
        return repr(e.value)
    if isinstance(e, Name):
        return e.value
    if isinstance(e, AwaitExpr):
        return f"await_result({_expr(e.expr)})"
    if isinstance(e, Unary):
        if e.op == "!":
            return f"(not {_expr(e.expr)})"
        return f"({e.op}{_expr(e.expr)})"
    if isinstance(e, Binary):
        if e.op == "??":
            left = _expr(e.left)
            return f"({left} if {left} is not None else {_expr(e.right)})"
        op = BIN_OP_MAP.get(e.op, e.op)
        return f"({_expr(e.left)} {op} {_expr(e.right)})"
    if isinstance(e, Call):
        name = e.resolved_name or _call_name(e.fn)
        name = {"print": "print_", "len": "len_"}.get(name, name)
        return f"{name}({', '.join(_expr(a) for a in e.args)})"
    if isinstance(e, IndexExpr):
        return f"({_expr(e.obj)})[{_expr(e.index)}]"
    if isinstance(e, FieldExpr):
        return f"({_expr(e.obj)}).{e.field}"
    if isinstance(e, ArrayLit):
        return f"[{', '.join(_expr(x) for x in e.elements)}]"
    raise CodegenError(_diag(e, f"unsupported expression {type(e).__name__}"))


def _target_expr(t):
    if isinstance(t, Name):
        return t.value
    if isinstance(t, IndexExpr):
        return f"({_expr(t.obj)})[{_expr(t.index)}]"
    if isinstance(t, FieldExpr):
        return f"({_expr(t.obj)}).{t.field}"
    return _expr(t)


def _stmt_py(st, ind):
    p = "    " * ind
    if isinstance(st, LetStmt):
        return [f"{p}{st.name} = {_expr(st.expr)}"]
    if isinstance(st, AssignStmt):
        return [f"{p}{_target_expr(st.target)} {st.op} {_expr(st.expr)}"]
    if isinstance(st, ReturnStmt):
        return [f"{p}return {_expr(st.expr) if st.expr else 'None'}"]
    if isinstance(st, BreakStmt):
        return [f"{p}break"]
    if isinstance(st, ContinueStmt):
        return [f"{p}continue"]
    if isinstance(st, DeferStmt):
        return [f"{p}_astra_defer_stack.append(lambda: {_expr(st.expr)})"]
    if isinstance(st, ComptimeStmt):
        return []
    if isinstance(st, ExprStmt):
        return [f"{p}{_expr(st.expr)}"]
    if isinstance(st, IfStmt):
        lines = [f"{p}if {_expr(st.cond)}:"]
        if st.then_body:
            for s in st.then_body:
                lines.extend(_stmt_py(s, ind + 1))
        else:
            lines.append(f"{'    ' * (ind + 1)}pass")
        if st.else_body:
            lines.append(f"{p}else:")
            for s in st.else_body:
                lines.extend(_stmt_py(s, ind + 1))
        return lines
    if isinstance(st, MatchStmt):
        lines = [f"{p}__match_value_{ind} = {_expr(st.expr)}"]
        for idx, (pat, body) in enumerate(st.arms):
            head = "if" if idx == 0 else "elif"
            lines.append(f"{p}{head} __match_value_{ind} == {_expr(pat)}:")
            if body:
                for s in body:
                    lines.extend(_stmt_py(s, ind + 1))
            else:
                lines.append(f"{'    ' * (ind + 1)}pass")
        if st.arms:
            lines.append(f"{p}else:")
            lines.append(f"{'    ' * (ind + 1)}pass")
        return lines
    if isinstance(st, WhileStmt):
        lines = [f"{p}while {_expr(st.cond)}:"]
        for s in st.body:
            lines.extend(_stmt_py(s, ind + 1))
        if not st.body:
            lines.append(f"{'    ' * (ind + 1)}pass")
        return lines
    if isinstance(st, ForStmt):
        if isinstance(st.init, LetStmt) and isinstance(st.init.expr, Name) and st.init.expr.value == "<iter>" and st.step is None:
            lines = [f"{p}for {st.init.name} in {_expr(st.cond)}:"]
            for s in st.body:
                lines.extend(_stmt_py(s, ind + 1))
            if not st.body:
                lines.append(f"{'    ' * (ind + 1)}pass")
            return lines
        lines = []
        if st.init:
            if isinstance(st.init, LetStmt):
                lines.extend(_stmt_py(st.init, ind))
            else:
                lines.append(f"{p}{_expr(st.init)}")
        lines.append(f"{p}while {_expr(st.cond) if st.cond else 'True'}:")
        if st.body:
            for s in st.body:
                lines.extend(_stmt_py(s, ind + 1))
        if st.step:
            if isinstance(st.step, AssignStmt):
                lines.extend(_stmt_py(st.step, ind + 1))
            else:
                lines.append(f"{'    ' * (ind + 1)}{_expr(st.step)}")
        if not st.body and st.step is None:
            lines.append(f"{'    ' * (ind + 1)}pass")
        return lines
    raise CodegenError(_diag(st, f"unsupported statement {type(st).__name__}"))


@dataclass
class _FnCtx:
    epilogue: str
    slots: dict[str, int]
    next_slot: int
    loop_stack: list[tuple[str, str]]
    next_label: int
    fn_names: set[str]


def to_x86_64(prog: Program, freestanding: bool = False) -> str:
    main_entry = "main"
    for item in prog.items:
        if isinstance(item, FnDecl) and item.name == "main":
            main_entry = item.symbol or item.name
            break
    lines: list[str] = []
    if freestanding:
        lines.append("section .text")
    else:
        lines += ["global _start", "section .text", "_start:", f"  call {main_entry}", "  mov rdi, rax", "  mov rax, 60", "  syscall", ""]
    fn_names = {(item.symbol or item.name) for item in prog.items if isinstance(item, FnDecl)}
    if freestanding and any((item.symbol or item.name) == "_start" for item in prog.items if isinstance(item, FnDecl)):
        lines.insert(0, "global _start")
    for item in prog.items:
        if isinstance(item, (StructDecl, EnumDecl, TypeAliasDecl, ImportDecl, ExternFnDecl)):
            continue
        if not isinstance(item, FnDecl):
            continue
        if item.async_fn:
            raise CodegenError(_diag(item, "async functions are not supported on x86_64 backend"))
        lines.extend(_x86_fn(item, fn_names))
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def _x86_fn(fn: FnDecl, fn_names: set[str]) -> list[str]:
    fn_name = fn.symbol or fn.name
    ctx = _FnCtx(epilogue=f".L_{fn_name}_epilogue", slots={}, next_slot=0, loop_stack=[], next_label=0, fn_names=fn_names)
    body: list[str] = []
    param_regs = ["rdi", "rsi", "rdx", "rcx", "r8", "r9"]
    if len(fn.params) > len(param_regs):
        raise CodegenError(_diag(fn, "x86_64 backend supports up to 6 parameters"))
    for idx, (name, typ) in enumerate(fn.params):
        if typ != "Int":
            raise CodegenError(_diag(fn, f"x86_64 backend only supports Int params, got {typ}"))
        slot = _alloc_slot(ctx, name)
        body += [f"  mov qword [rbp-{slot}], {param_regs[idx]}"]
    for st in fn.body:
        body.extend(_x86_stmt(st, ctx))
    lines = [f"{fn_name}:", "  push rbp", "  mov rbp, rsp"]
    frame = max(16, ((ctx.next_slot + 15) // 16) * 16)
    lines.append(f"  sub rsp, {frame}")
    lines.extend(body)
    lines += [f"{ctx.epilogue}:", "  mov rsp, rbp", "  pop rbp", "  ret"]
    return lines


def _alloc_slot(ctx: _FnCtx, name: str) -> int:
    if name in ctx.slots:
        return ctx.slots[name]
    ctx.next_slot += 8
    ctx.slots[name] = ctx.next_slot
    return ctx.next_slot


def _require_name_slot(name: str, ctx: _FnCtx, node: Any) -> int:
    if name not in ctx.slots:
        raise CodegenError(_diag(node, f"undefined local {name} for x86_64 backend"))
    return ctx.slots[name]


def _label(ctx: _FnCtx, prefix: str) -> str:
    ctx.next_label += 1
    return f".L_{prefix}_{ctx.next_label}"


def _x86_stmt(st, ctx: _FnCtx) -> list[str]:
    if isinstance(st, LetStmt):
        if st.type_name not in {None, "Int"}:
            raise CodegenError(_diag(st, "x86_64 backend only supports Int locals"))
        slot = _alloc_slot(ctx, st.name)
        code = _x86_expr(st.expr, ctx)
        return code + [f"  mov qword [rbp-{slot}], rax"]
    if isinstance(st, AssignStmt):
        if not isinstance(st.target, Name):
            raise CodegenError(_diag(st, "x86_64 backend only supports assignment to local names"))
        slot = _require_name_slot(st.target.value, ctx, st)
        code = _x86_expr(st.expr, ctx)
        if st.op != "=":
            code += [f"  mov rbx, qword [rbp-{slot}]"]
            if st.op == "+=":
                code += ["  add rbx, rax", "  mov rax, rbx"]
            elif st.op == "-=":
                code += ["  sub rbx, rax", "  mov rax, rbx"]
            elif st.op == "*=":
                code += ["  imul rbx, rax", "  mov rax, rbx"]
            else:
                raise CodegenError(_diag(st, f"unsupported assignment op {st.op} on x86_64 backend"))
        return code + [f"  mov qword [rbp-{slot}], rax"]
    if isinstance(st, ReturnStmt):
        if st.expr is None:
            return ["  xor rax, rax", f"  jmp {ctx.epilogue}"]
        return _x86_expr(st.expr, ctx) + [f"  jmp {ctx.epilogue}"]
    if isinstance(st, ExprStmt):
        return _x86_expr(st.expr, ctx)
    if isinstance(st, IfStmt):
        lbl_else = _label(ctx, "if_else")
        lbl_end = _label(ctx, "if_end")
        code = _x86_expr(st.cond, ctx)
        code += ["  cmp rax, 0", f"  je {lbl_else}"]
        for s in st.then_body:
            code += _x86_stmt(s, ctx)
        code += [f"  jmp {lbl_end}", f"{lbl_else}:"]
        for s in st.else_body:
            code += _x86_stmt(s, ctx)
        code += [f"{lbl_end}:"]
        return code
    if isinstance(st, WhileStmt):
        lbl_begin = _label(ctx, "while_begin")
        lbl_end = _label(ctx, "while_end")
        code = [f"{lbl_begin}:"]
        code += _x86_expr(st.cond, ctx)
        code += ["  cmp rax, 0", f"  je {lbl_end}"]
        ctx.loop_stack.append((lbl_end, lbl_begin))
        for s in st.body:
            code += _x86_stmt(s, ctx)
        ctx.loop_stack.pop()
        code += [f"  jmp {lbl_begin}", f"{lbl_end}:"]
        return code
    if isinstance(st, ForStmt):
        code: list[str] = []
        if st.init is not None:
            if isinstance(st.init, LetStmt):
                code += _x86_stmt(st.init, ctx)
            else:
                code += _x86_expr(st.init, ctx)
        lbl_begin = _label(ctx, "for_begin")
        lbl_cont = _label(ctx, "for_cont")
        lbl_end = _label(ctx, "for_end")
        code += [f"{lbl_begin}:"]
        if st.cond is not None:
            code += _x86_expr(st.cond, ctx)
            code += ["  cmp rax, 0", f"  je {lbl_end}"]
        ctx.loop_stack.append((lbl_end, lbl_cont))
        for s in st.body:
            code += _x86_stmt(s, ctx)
        ctx.loop_stack.pop()
        code += [f"{lbl_cont}:"]
        if st.step is not None:
            if isinstance(st.step, AssignStmt):
                code += _x86_stmt(st.step, ctx)
            else:
                code += _x86_expr(st.step, ctx)
        code += [f"  jmp {lbl_begin}", f"{lbl_end}:"]
        return code
    if isinstance(st, BreakStmt):
        if not ctx.loop_stack:
            raise CodegenError(_diag(st, "break outside loop"))
        return [f"  jmp {ctx.loop_stack[-1][0]}"]
    if isinstance(st, ContinueStmt):
        if not ctx.loop_stack:
            raise CodegenError(_diag(st, "continue outside loop"))
        return [f"  jmp {ctx.loop_stack[-1][1]}"]
    if isinstance(st, ComptimeStmt):
        return []
    if isinstance(st, DeferStmt):
        raise CodegenError(_diag(st, "defer is not supported on x86_64 backend"))
    raise CodegenError(_diag(st, f"{type(st).__name__} is not supported on x86_64 backend"))


def _x86_expr(e, ctx: _FnCtx) -> list[str]:
    if isinstance(e, Literal):
        if isinstance(e.value, bool):
            return [f"  mov rax, {1 if e.value else 0}"]
        if not isinstance(e.value, int):
            raise CodegenError(_diag(e, "x86_64 backend only supports integer literals"))
        return [f"  mov rax, {e.value}"]
    if isinstance(e, BoolLit):
        return [f"  mov rax, {1 if e.value else 0}"]
    if isinstance(e, Name):
        slot = _require_name_slot(e.value, ctx, e)
        return [f"  mov rax, qword [rbp-{slot}]"]
    if isinstance(e, Unary):
        code = _x86_expr(e.expr, ctx)
        if e.op == "-":
            return code + ["  neg rax"]
        if e.op == "!":
            return code + ["  cmp rax, 0", "  sete al", "  movzx rax, al"]
        raise CodegenError(_diag(e, f"unary operator {e.op} is unsupported on x86_64 backend"))
    if isinstance(e, Binary):
        code = _x86_expr(e.left, ctx)
        code += ["  push rax"]
        code += _x86_expr(e.right, ctx)
        code += ["  mov rbx, rax", "  pop rax"]
        op = e.op
        if op == "+":
            return code + ["  add rax, rbx"]
        if op == "-":
            return code + ["  sub rax, rbx"]
        if op == "*":
            return code + ["  imul rax, rbx"]
        if op == "/":
            return code + ["  cqo", "  idiv rbx"]
        if op == "%":
            return code + ["  cqo", "  idiv rbx", "  mov rax, rdx"]
        if op in {"==", "!=", "<", "<=", ">", ">="}:
            cond = {"==": "sete", "!=": "setne", "<": "setl", "<=": "setle", ">": "setg", ">=": "setge"}[op]
            return code + ["  cmp rax, rbx", f"  {cond} al", "  movzx rax, al"]
        if op == "&&":
            return code + ["  cmp rax, 0", "  setne al", "  movzx rax, al", "  cmp rbx, 0", "  setne bl", "  and al, bl", "  movzx rax, al"]
        if op == "||":
            return code + ["  cmp rax, 0", "  setne al", "  cmp rbx, 0", "  setne bl", "  or al, bl", "  movzx rax, al"]
        raise CodegenError(_diag(e, f"binary operator {op} is unsupported on x86_64 backend"))
    if isinstance(e, Call):
        if not isinstance(e.fn, Name):
            raise CodegenError(_diag(e, "x86_64 backend only supports direct function calls"))
        target_name = e.resolved_name or e.fn.value
        if target_name not in ctx.fn_names:
            raise CodegenError(_diag(e, f"x86_64 backend cannot call unresolved function {target_name}"))
        regs = ["rdi", "rsi", "rdx", "rcx", "r8", "r9"]
        if len(e.args) > len(regs):
            raise CodegenError(_diag(e, "x86_64 backend supports up to 6 call arguments"))
        code: list[str] = []
        for arg in e.args:
            code += _x86_expr(arg, ctx)
            code += ["  push rax"]
        for i in range(len(e.args) - 1, -1, -1):
            code += [f"  pop {regs[i]}"]
        code += [f"  call {target_name}"]
        return code
    raise CodegenError(_diag(e, f"{type(e).__name__} is unsupported on x86_64 backend"))
